### ISSUE TITLE
`flshattF@v2.3.6` is not supported because:     max(query.shape[-1] != value.shape[-1]) > 256

### ISSUE THREAD

**Issue by qianghuangwhu** [facebookresearch/xformers#1027]
# 🐛 Bug

**Why is "memory_efficient_attention" not supported for dimensions greater than 256，for example 512?**

```bash
Traceback (most recent call last):
  File "/data/scripts/xformer_test.py", line 32, in <module>
    out = fmha.memory_efficient_attention(q, k, v, attn_bias=attn_bias, op=(xops.fmha.flash.FwOp, xops.fmha.flash.BwOp))
  File "/software/Anaconda3/envs/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 223, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/software/Anaconda3/envs/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 326, in _memory_efficient_attention
    return _fMHA.apply(
  File "/software/Anaconda3/envs/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 42, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "/software/Anaconda3/envs/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 353, in _memory_efficient_attention_forward_requires_grad
    _ensure_op_supports_or_raise(ValueError, "memory_efficient_attention", op, inp)
  File "/software/Anaconda3/envs/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 39, in _ensure_op_supports_or_raise
    raise exc_type(
ValueError: Operator `memory_efficient_attention` does not support inputs:
     query       : shape=(3, 32, 2, 4, 512) (torch.float16)
     key         : shape=(3, 32, 2, 4, 512) (torch.float16)
     value       : shape=(3, 32, 2, 4, 512) (torch.float16)
     attn_bias   : <class 'xformers.ops.fmha.attn_bias.LowerTriangularMask'>
     p           : 0.0
`flshattF@v2.3.6` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 256
```

## Command

**running code**

```python
import torch
import xformers.ops as xops

B, M, K = 3, 32, 512
kwargs = dict(device="cuda", dtype=torch.float16)
q = torch.randn([B, M, 8, K], **kwargs)
k = torch.randn([B, M, 2, K], **kwargs)
v = torch.randn([B, M, 2, K], **kwargs)
out_gqa = xops.memory_efficient_attention(
    q.reshape([B, M, 2, 4, K]),
    k.reshape([B, M, 2, 1, K]).expand([B, M, 2, 4, K]),
    v.reshape([B, M, 2, 1, K]).expand([B, M, 2, 4, K]),
    attn_bias=xops.LowerTriangularMask(),
    op=(xops.fmha.flash.FwOp, xops.fmha.flash.BwOp)
)
print(out_gqa.shape)
```

## Environment

- torch==2.1.2+cu118
- xformers==0.0.23.post1+cu118
- A100 GPU with 80GB
- I have installed flash-attn==2.3.6

**Comment by danthe3rd** [comment]
Hi,
Flash-Attention does not support head embedding > 256. What kind of model are you using? Most of the models use K<=128, some up to 256 but I've never seen 512.

**Comment by qianghuangwhu** [comment]
> Hi, Flash-Attention does not support head embedding > 256. What kind of model are you using? Most of the models use K<=128, some up to 256 but I've never seen 512.

@danthe3rd Oh oh, I understand, you are right, I looked at the models llama2 and Qwen2, for example. The dimensions of each of their heads are indeed 128, and there are very few models that exceed 256. Thank you very much for your reply.
