### ISSUE TITLE
Problem about the xformer 0.0.20, torch 2.0.1, need help!!!

### ISSUE THREAD

**Issue by liujf69** [facebookresearch/xformers#1050]
when I install xformer 0.0.20 and torch 2.0.1, I met the following problem:
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hadoop-waimai-aigc/.local/lib/python3.9/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or director
```
when I install xformer 0.0.19 and torch 2.0.0, import torch is ok, but still have the following problem:
```
  File "/home/hadoop-waimai-aigc/.local/lib/python3.9/site-packages/diffusers/models/attention_processor.py", line 1144, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "/home/hadoop-waimai-aigc/.local/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 192, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/home/hadoop-waimai-aigc/.local/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 290, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/home/hadoop-waimai-aigc/.local/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 310, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "/home/hadoop-waimai-aigc/.local/lib/python3.9/site-packages/xformers/ops/fmha/cutlass.py", line 175, in apply
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "/usr/local/conda/lib/python3.9/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by danthe3rd** [comment]
Hi,
We don't support older versions of xFormers, because bugs have most-likely been fixed in later versions. Please open a new issue if you still have bugs with latest pytorch/xformers.
