### ISSUE TITLE
I am unable to install the xformers

### ISSUE THREAD

**Issue by MrHorakhty** [facebookresearch/xformers#1063]
# ❓ Questions and Help
I have CUDA 12.4 and pytorch nightly build compatible with it. However I am getting this error when trying to install xformers.

### 
C:\Windows\system32>pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
Using pip 24.1.1 from C:\Users\emire\miniconda3\Lib\site-packages\pip (python 3.12)
Collecting xformers
  Cloning https://github.com/facebookresearch/xformers.git (to revision main) to c:\users\emire\appdata\local\temp\pip-install-766pdvg_\xformers_e75d2bddaecd42949aefb9b7175d352e
  Running command git version
  git version 2.45.2.windows.1
  Running command git clone --filter=blob:none https://github.com/facebookresearch/xformers.git 'C:\Users\emire\AppData\Local\Temp\pip-install-766pdvg_\xformers_e75d2bddaecd42949aefb9b7175d352e'
  Cloning into 'C:\Users\emire\AppData\Local\Temp\pip-install-766pdvg_\xformers_e75d2bddaecd42949aefb9b7175d352e'...
  Updating files:   0% (2/985)
  Updating files:   1% (10/985)
  Updating files:   2% (20/985)
  Updating files:   3% (30/985)
  Updating files:   4% (40/985)
  Updating files:   5% (50/985)
  Updating files:   6% (60/985)
  Updating files:   7% (69/985)
  Updating files:   8% (79/985)
  Updating files:   9% (89/985)
  Updating files:  10% (99/985)
  Updating files:  11% (109/985)
  Updating files:  12% (119/985)
  Updating files:  13% (129/985)
  Updating files:  14% (138/985)
  Updating files:  15% (148/985)
  Updating files:  16% (158/985)
  Updating files:  17% (168/985)
  Updating files:  18% (178/985)
  Updating files:  19% (188/985)
  Updating files:  20% (197/985)
  Updating files:  21% (207/985)
  Updating files:  22% (217/985)
  Updating files:  23% (227/985)
  Updating files:  24% (237/985)
  Updating files:  25% (247/985)
  Updating files:  26% (257/985)
  Updating files:  27% (266/985)
  Updating files:  28% (276/985)
  Updating files:  29% (286/985)
  Updating files:  30% (296/985)
  Updating files:  31% (306/985)
  Updating files:  32% (316/985)
  Updating files:  33% (326/985)
  Updating files:  34% (335/985)
  Updating files:  35% (345/985)
  Updating files:  36% (355/985)
  Updating files:  37% (365/985)
  Updating files:  38% (375/985)
  Updating files:  39% (385/985)
  Updating files:  40% (394/985)
  Updating files:  41% (404/985)
  Updating files:  42% (414/985)
  Updating files:  43% (424/985)
  Updating files:  44% (434/985)
  Updating files:  45% (444/985)
  Updating files:  46% (454/985)
  Updating files:  47% (463/985)
  Updating files:  48% (473/985)
  Updating files:  49% (483/985)
  Updating files:  50% (493/985)
  Updating files:  51% (503/985)
  Updating files:  52% (513/985)
  Updating files:  53% (523/985)
  Updating files:  54% (532/985)
  Updating files:  55% (542/985)
  Updating files:  56% (552/985)
  Updating files:  57% (562/985)
  Updating files:  58% (572/985)
  Updating files:  59% (582/985)
  Updating files:  60% (591/985)
  Updating files:  61% (601/985)
  Updating files:  62% (611/985)
  Updating files:  63% (621/985)
  Updating files:  64% (631/985)
  Updating files:  65% (641/985)
  Updating files:  66% (651/985)
  Updating files:  67% (660/985)
  Updating files:  68% (670/985)
  Updating files:  69% (680/985)
  Updating files:  70% (690/985)
  Updating files:  71% (700/985)
  Updating files:  72% (710/985)
  Updating files:  73% (720/985)
  Updating files:  74% (729/985)
  Updating files:  75% (739/985)
  Updating files:  76% (749/985)
  Updating files:  77% (759/985)
  Updating files:  78% (769/985)
  Updating files:  79% (779/985)
  Updating files:  80% (788/985)
  Updating files:  81% (798/985)
  Updating files:  82% (808/985)
  Updating files:  83% (818/985)
  Updating files:  84% (828/985)
  Updating files:  85% (838/985)
  Updating files:  86% (848/985)
  Updating files:  87% (857/985)
  Updating files:  88% (867/985)
  Updating files:  89% (877/985)
  Updating files:  90% (887/985)
  Updating files:  91% (897/985)
  Updating files:  92% (907/985)
  Updating files:  93% (917/985)
  Updating files:  94% (926/985)
  Updating files:  95% (936/985)
  Updating files:  96% (946/985)
  Updating files:  97% (956/985)
  Updating files:  98% (966/985)
  Updating files:  99% (976/985)
  Updating files: 100% (985/985)
  Updating files: 100% (985/985), done.
  Running command git show-ref main
  b63143b3285616596af744beb8aff5cc6a49d9c4 refs/heads/main
  b63143b3285616596af744beb8aff5cc6a49d9c4 refs/remotes/origin/main
  Running command git symbolic-ref -q HEAD
  refs/heads/main
  Resolved https://github.com/facebookresearch/xformers.git to commit b63143b3285616596af744beb8aff5cc6a49d9c4
  Running command git submodule update --init --recursive -q
  Running command git rev-parse HEAD
  b63143b3285616596af744beb8aff5cc6a49d9c4
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\emire\AppData\Local\Temp\pip-install-766pdvg_\xformers_e75d2bddaecd42949aefb9b7175d352e\setup.py", line 541, in <module>
      extensions, extensions_metadata = get_extensions()
                                        ^^^^^^^^^^^^^^^^
    File "C:\Users\emire\AppData\Local\Temp\pip-install-766pdvg_\xformers_e75d2bddaecd42949aefb9b7175d352e\setup.py", line 335, in get_extensions
      cuda_version = get_cuda_version(CUDA_HOME)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\emire\AppData\Local\Temp\pip-install-766pdvg_\xformers_e75d2bddaecd42949aefb9b7175d352e\setup.py", line 130, in get_cuda_version
      raw_output = subprocess.check_output([nvcc_bin, "-V"], universal_newlines=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\emire\miniconda3\Lib\subprocess.py", line 466, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\emire\miniconda3\Lib\subprocess.py", line 548, in run
      with Popen(*popenargs, **kwargs) as process:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\emire\miniconda3\Lib\subprocess.py", line 1026, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\emire\miniconda3\Lib\subprocess.py", line 1538, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\emire\miniconda3\python.exe' -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'C:\\Users\\emire\\AppData\\Local\\Temp\\pip-install-766pdvg_\\xformers_e75d2bddaecd42949aefb9b7175d352e\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base 'C:\Users\emire\AppData\Local\Temp\pip-pip-egg-info-mgznj352'
  cwd: C:\Users\emire\AppData\Local\Temp\pip-install-766pdvg_\xformers_e75d2bddaecd42949aefb9b7175d352e\\
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
###

**Comment by kfantific** [comment]
they dont support 12.4  ...yet

**Comment by danthe3rd** [comment]
Hi,
Have you tried installing xFormers with cuda 12.1? It should be compatible with cuda 12.4.
You can install it with:
```
pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121
```
