### ISSUE TITLE
USE_FLASH_ATTENTION was not enabled for build

### ISSUE THREAD

**Issue by MrHorakhty** [facebookresearch/xformers#1069]
# ❓ Questions and Help
I have been getting this error when I try to use KSampler gpt said it was about USE_FLASH_ATTENTION tag so I built it with the tag and got this as a confirmation.

"(venv) C:\Games\Stable Diffusion\stable-diffusion-webui\venv\Scripts>python -c "import xformers.ops as xops; print('Flash Attention is enabled.' if hasattr(xops, 'memory_efficient_attention') else 'Flash Attention is NOT enabled.')"
C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: torch.library.impl_abstract was renamed to torch.library.register_fake. Please use that instead; we will remove torch.library.impl_abstract in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: torch.library.impl_abstract was renamed to torch.library.register_fake. Please use that instead; we will remove torch.library.impl_abstract in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\swiglu_op.py:128: FutureWarning: torch.cuda.amp.custom_fwd(args...) is deprecated. Please use torch.amp.custom_fwd(args..., device_type='cuda') instead.
  def forward(cls, ctx, x, w1, b1, w2, b2, w3, b3):
C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\swiglu_op.py:149: FutureWarning: torch.cuda.amp.custom_bwd(args...) is deprecated. Please use torch.amp.custom_bwd(args..., device_type='cuda') instead.
  def backward(cls, ctx, dx5):
Flash Attention is enabled."

However I am still getting this error when I try to use KSampler.
"Error occurred when executing KSampler:

USE_FLASH_ATTENTION was not enabled for build.

File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\nodes.py", line 1373, in sample
return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\nodes.py", line 1343, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
raise e
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 410, in motion_sample
return orig_comfy_sample(model, noise, *args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\sample.py", line 43, in sample
samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 801, in sample
return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 703, in sample
return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 690, in sample
output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 669, in inner_sample
samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 574, in sample
samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\k_diffusion\sampling.py", line 143, in sample_euler
denoised = model(x, sigma_hat * s_in, **extra_args)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 297, in __call__
out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 656, in __call__
return self.predict_noise(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 659, in predict_noise
return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 277, in sampling_function
out = calc_cond_batch(model, conds, x, timestep, model_options)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\samplers.py", line 226, in calc_cond_batch
output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\model_base.py", line 114, in apply_model
model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1714, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1725, in _call_impl
return forward_call(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 852, in forward
h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 40, in forward_timestep_embed
x = layer(x, context, time_context, num_video_frames, image_only_indicator, transformer_options)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1714, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1725, in _call_impl
return forward_call(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\ldm\modules\attention.py", line 839, in forward
x = block(
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1714, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1725, in _call_impl
return forward_call(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\ldm\modules\attention.py", line 581, in forward
n = self.attn1(n, context=context_attn1, value=value_attn1)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1714, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1725, in _call_impl
return forward_call(*args, **kwargs)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\ldm\modules\attention.py", line 475, in forward
out = optimized_attention(q, k, v, self.heads, attn_precision=self.attn_precision)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\comfy\ldm\modules\attention.py", line 380, in attention_xformers
out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=mask)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 276, in memory_efficient_attention
return _memory_efficient_attention(
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 395, in _memory_efficient_attention
return _memory_efficient_attention_forward(
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 418, in _memory_efficient_attention_forward
out, *_ = op.apply(inp, needs_gradient=False)
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\flash.py", line 731, in apply
out, softmax_lse, rng_state = cls.OPERATOR(
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 1064, in __call__
return self_._op(*args, **(kwargs or {}))
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\flash.py", line 129, in _flash_fwd
) = torch.ops.aten._flash_attention_forward(
File "C:\Games\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 1064, in __call__
return self_._op(*args, **(kwargs or {}))"

Any help would be appreciated.

**Comment by danthe3rd** [comment]
This is related to https://github.com/facebookresearch/xformers/issues/1073, which is fixed now. Please upgrade xFormers
