### ISSUE TITLE
Local attention mask size mismatch

### ISSUE THREAD

**Issue by samuelwheeler** [facebookresearch/xformers#1076]
# ❓ Questions and Help
I am testing out the local attention implementation, trying to use a casual sliding window with window size 128. I get a size mismatch error from the following code:

```
import torch
from xformers.components.attention.local import LocalAttention

atn = LocalAttention(causal = True, window_size = 128)
q,k,v = torch.randn(2,8, 512 , 32),torch.randn(2, 8, 512, 32),torch.randn(2, 8, 512, 32)
out = atn(q,k,v)
```

Here's the stack trace:

> Traceback (most recent call last):
  File "/home/sww/hybrid_long_context/testing_sa.py", line 6, in <module>
    out = atn(q,k,v)
          ^^^^^^^^^^
  File "/home/sww/.local/polaris/conda/2024-04-29/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sww/.local/polaris/conda/2024-04-29/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sww/.local/polaris/conda/2024-04-29/lib/python3.11/site-packages/xformers/components/attention/local.py", line 118, in forward
    return scaled_dot_product_attention(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sww/.local/polaris/conda/2024-04-29/lib/python3.11/site-packages/xformers/components/attention/core.py", line 325, in scaled_dot_product_attention
    att = scaled_query_key_softmax(q, k, att_mask=att_mask)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sww/.local/polaris/conda/2024-04-29/lib/python3.11/site-packages/xformers/components/attention/core.py", line 223, in scaled_query_key_softmax
    att = _matmul_with_mask(q, k.transpose(-2, -1), mask)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sww/.local/polaris/conda/2024-04-29/lib/python3.11/site-packages/xformers/components/attention/core.py", line 113, in _matmul_with_mask
    att += mask
RuntimeError: The size of tensor a (512) must match the size of tensor b (8) at non-singleton dimension 3

Thanks for any help on this.

**Comment by samuelwheeler** [comment]
The solution was to use the MultiHeadDispatch, as describe in the howto file.
