### ISSUE TITLE
I cannot run xformers on an AMD Radeon RX 6600 with torch 2.4.1

### ISSUE THREAD

**Issue by renich** [facebookresearch/xformers#1116]
# ❓ Questions and Help
I am not an expert and I dunno what is happening. 

Basically, I am trying to run a model and, if I have xformers installed, i get this error. The problem goes away when I remove it from my venv. 

My environment is: 

* Fedora 41 (beta)
* Python 3.12.6

```
$ pip freeze
accelerate==0.34.2
aiohappyeyeballs==2.4.2
aiohttp==3.10.7
aiosignal==1.3.1
attrs==24.2.0
certifi==2024.8.30
charset-normalizer==3.3.2
colored==2.2.4
compel==2.0.3
datasets==3.0.1
diffusers==0.30.3
dill==0.3.8
filelock==3.16.1
frozenlist==1.4.1
fsspec==2024.6.1
huggingface-hub==0.25.1
idna==3.10
importlib_metadata==8.5.0
Jinja2==3.1.4
MarkupSafe==2.1.5
mpmath==1.3.0
multidict==6.1.0
multiprocess==0.70.16
networkx==3.3
numpy==2.1.1
packaging==24.1
pandas==2.2.3
pillow==10.4.0
protobuf==5.28.2
psutil==6.0.0
pyarrow==17.0.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
pytorch-triton-rocm==3.0.0
pytz==2024.2
PyYAML==6.0.2
regex==2024.9.11
requests==2.32.3
safetensors==0.4.5
sentencepiece==0.2.0
setuptools==75.1.0
six==1.16.0
sympy==1.13.3
tokenizers==0.20.0
tomesd==0.1.3
torch==2.4.1+rocm6.1
torchaudio==2.4.1+rocm6.1
torchvision==0.19.1+rocm6.1
tqdm==4.66.5
transformers==4.45.1
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
xformers==0.0.28.post1
xxhash==3.5.0
yarl==1.13.1
zipp==3.20.2
```

The error:

```
$ ./mklan.py 
Fetching 17 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 237677.23it/s]
Loading pipeline components...:   0%|                                                                                                                                                          | 0/7 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel: 
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 11.96it/s]
Traceback (most recent call last):
  File "/home/renich/tmp/hf/amd/./mklan.py", line 47, in <module>
    pipeline.enable_xformers_memory_efficient_attention()
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/pipelines/pipeline_utils.py", line 1663, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/pipelines/pipeline_utils.py", line 1689, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/pipelines/pipeline_utils.py", line 1679, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 222, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 222, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/attention_processor.py", line 337, in set_use_memory_efficient_attention_xformers
    raise e
  File "/home/renich/tmp/hf/amd/venv/lib64/python3.12/site-packages/diffusers/models/attention_processor.py", line 332, in set_use_memory_efficient_attention_xformers
    torch.randn((1, 2, 40), device="cuda"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

**Comment by lw** [comment]
I don't believe this error is directly related to xFormers: the stack trace doesn't include any of xFormers code and, in fact, the error seems to occur when invoking a standard PyTorch function (`torch.randn`). If so, you will have to follow up with the folks from the codebase you're using (`diffusers`), or with PyTorch directly.

Did you follow the suggestion mentioned in the log, of setting `AMD_SERIALIZE_KERNEL=3`?

**Comment by renich** [comment]
Yes. I did. I can send you the output if you like. 

```
$ AMD_SERIALIZE_KERNEL=3 ./sdcli.py 
We're using AMD! Yay! \o/
Fetching 17 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 85907.43it/s]
Loading pipeline components...:   0%|                                                                                                                                                          | 0/7 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel: 
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 14.64it/s]
Traceback (most recent call last):
  File "/home/renich/Projects/hf/./sdcli.py", line 3, in <module>
    from modules.init import *
  File "/home/renich/Projects/hf/modules/init.py", line 65, in <module>
    pipeline.enable_xformers_memory_efficient_attention()
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/pipelines/pipeline_utils.py", line 1663, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/pipelines/pipeline_utils.py", line 1689, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/pipelines/pipeline_utils.py", line 1679, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 222, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 222, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 218, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/attention_processor.py", line 337, in set_use_memory_efficient_attention_xformers
    raise e
  File "/home/renich/Projects/hf/venv/lib64/python3.12/site-packages/diffusers/models/attention_processor.py", line 332, in set_use_memory_efficient_attention_xformers
    torch.randn((1, 2, 40), device="cuda"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

I will take the issue to huggingface or pytorch then, as you suggest. 

Thank you for your time.
