### ISSUE TITLE
Cann't install xformers==0.0.28.post2

### ISSUE THREAD

**Issue by Wiselnn570** [facebookresearch/xformers#1139]
# 🐛 Bug

Recently I try to install vllm which relies on xformers==0.0.28.post2, but the process failed when tries to install this specific version.

## My Environment
torch            2.4.0

# Output
pip install xformers==0.0.28.post2 --no-cache-dir
Collecting xformers==0.0.28.post2
  Downloading xformers-0.0.28.post2.tar.gz (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-icn0nd6t/xformers_0da9b426d1d34585902a4f53b0f2e43e/setup.py", line 24, in <module>
          import torch
        File "/mnt/petrelfs/weixilin/miniconda3/envs/qwen2-vl/lib/python3.10/site-packages/torch/__init__.py", line 290, in <module
>
          from torch._C import *  # noqa: F403
      ImportError: /mnt/petrelfs/weixilin/miniconda3/envs/qwen2-vl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so: undefin
ed symbol: ncclCommRegister

**Comment by lw** [comment]
Your issue is with PyTorch, not with xFormers.

Also, xFormers 0.0.28.post2 is only compatible with PyTorch 2.5.0. You should let pip choose which version to install.
