### ISSUE TITLE
Pre-commit broken on seed isort

### ISSUE THREAD

**Issue by fmassa** [facebookresearch/xformers#194]
# 🐛 Bug

I just enabled the `pre-commit` hooks in my environment following the docs, and they seem to raise an error in an unrelated part of the codebase.

This is the error message I get after a `git commit`:

```
Trim Trailing Whitespace.................................................Passed
Check python ast.........................................................Passed
Check for merge conflicts................................................Passed
Don't commit to branch...................................................Passed
Check for added large files..............................................Passed
Fix End of Files.........................................................Passed
black....................................................................Passed
flake8...................................................................Passed
seed isort known_third_party.............................................Failed
- hook id: seed-isort-config
- exit code: 1

Traceback (most recent call last):
  File "/private/home/fmassa/.cache/pre-commit/repohjnsozm1/py_env-python3/bin/seed-isort-config", line 8, in <module>
    sys.exit(main())
  File "/private/home/fmassa/.cache/pre-commit/repohjnsozm1/py_env-python3/lib/python3.8/site-packages/seed_isort_config.py", line 112, in main
    third_party = third_party_imports(filenames, appdirs)
  File "/private/home/fmassa/.cache/pre-commit/repohjnsozm1/py_env-python3/lib/python3.8/site-packages/seed_isort_config.py", line 60, in third_party_imports
    visitor.visit(ast.parse(f.read(), filename=filename))
  File "/private/home/fmassa/.conda/envs/xformers/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/private/home/fmassa/.conda/envs/xformers/lib/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/private/home/fmassa/.conda/envs/xformers/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/private/home/fmassa/.cache/pre-commit/repohjnsozm1/py_env-python3/lib/python3.8/site-packages/seed_isort_config.py", line 42, in visit_Import
    self._maybe_append_name(name.name)
  File "/private/home/fmassa/.cache/pre-commit/repohjnsozm1/py_env-python3/lib/python3.8/site-packages/seed_isort_config.py", line 35, in _maybe_append_name
    imp_type = classify_import(name, self.appdirs)
  File "/private/home/fmassa/.cache/pre-commit/repohjnsozm1/py_env-python3/lib/python3.8/site-packages/aspy/refactor_imports/classify.py", line 135, in classify_import
    found, module_path, is_builtin = _get_module_info(
  File "/private/home/fmassa/.cache/pre-commit/repohjnsozm1/py_env-python3/lib/python3.8/site-packages/aspy/refactor_imports/classify.py", line 103, in _get_module_info
    assert spec.submodule_search_locations is not None
AssertionError

isort....................................................................Passed
mypy.....................................................................Passed
```

**Comment by blefaudeux** [comment]
oh interesting, I don't think that I've ever seen that one :/ looks like something which broke upstream

**Comment by blefaudeux** [comment]
could you test on a newer python, like 3.9 ? Looks like it could be related to [importlib](https://github.com/pyinstaller/pyinstaller/commit/3fb624db62fd187a1dea1dee896b5fe8f3388bbb?branch=3fb624db62fd187a1dea1dee896b5fe8f3388bbb), although this is all new to me

**Comment by xwhan** [comment]
I got the same error when using pre-commit :)

**Comment by blefaudeux** [comment]
looks like we're not the only ones ([see](https://github.com/asottile/aspy.refactor_imports/issues/110)). Maybe that we could remove that step and trust black for all the import ordering for instance ? I did not have much time to look into this, sorry about that

**Comment by blefaudeux** [comment]
ah wait, it's not isort directly but this 'seed isort' step, looking into that and fixing this

**Comment by blefaudeux** [comment]
ok, depends on [this](https://github.com/asottile-archive/seed-isort-config) which is deprecated
