### ISSUE TITLE
fourier_mix attention does not support mixed precision training

### ISSUE THREAD

**Issue by Tomsen1410** [facebookresearch/xformers#256]
Fourier mix attention does not support half precision.

```Traceback (most recent call last):
 ...
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/muzik/src/modules/xformer/custom_block_factory.py", line 196, in forward
    x = self.mha(q, k, v, att_mask=att_mask)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/muzik/src/modules/xformer/custom_multi_head_dispatch.py", line 254, in forward
    y = self.attention(q=q, k=k, v=v, att_mask=att_mask)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/xformers/components/attention/fourier_mix.py", line 25, in forward
    att = torch.fft.fft2(q).real
RuntimeError: Unsupported dtype Half```

**Comment by blefaudeux** [comment]
thanks for the report ! Looks like it's pretty low level, in the fft op, I'll have a look

**Comment by blefaudeux** [comment]
fixed in an incoming branch @Tomsen1410, not a big issue (we can force this very line to stay fp32 and keep AMP, unless you want to use that with the whole model being half, but guess is no)

**Comment by blefaudeux** [comment]
@Tomsen1410 can you confirm that it's all good on your end ?
