### ISSUE TITLE
Support Windows and ideally build wheels for it

### ISSUE THREAD

**Issue by C43H66N12O12S2** [facebookresearch/xformers#437]
# 🚀 Feature

Supporting Windows in xformers.

## Motivation

xformers provide excellent tools to increase the speed of inference, for example close to 2x in Stable Diffusion. Sadly, it lacks Windows support. This has barred us from using it on https://github.com/AUTOMATIC1111/stable-diffusion-webui as most users and developers (including myself) use Windows.

## Pitch

Currently, xformers will fail to compile on Windows for a multitude of errors, some of which are trivial but most are not. Enabling Windows usage by fixing these errors and ideally distributing Windows wheels would allow projects to make xformers a necessary requirement & use it.

## Additional context
cc. @fmassa

**Comment by fmassa** [comment]
Thanks for opening this issue!

We are working on building conda packages for xformers https://github.com/facebookresearch/xformers/pull/407, and will be cutting a new release in https://github.com/facebookresearch/xformers/pull/435 that will make users be able to install through `pip` (although it will still compile the wheels locally for now).

For the windows support, can you maybe post a stack trace of the errors you get when compiling xformers?

@danthe3rd do you happen to know if CUTLASS supports Windows?

**Comment by C43H66N12O12S2** [comment]
By default, compilation will error out while building flash attention - this is due to a MSVC quirk with std::conditional. When that is fixed, xformers will give these errors:

```
C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\attention_scaling_coefs_updater.h(137): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\attention_scaling_coefs_updater.h(217): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\attention_scaling_coefs_updater.h(328): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\attention_scaling_coefs_updater.h(330): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\mma_from_smem.h(1040): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\../kernel_forward.h(74): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\../kernel_forward.h(75): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\../kernel_forward.h(181): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\../kernel_forward.h(250): error: expected a comma (the one-argument version of static_assert is not enabled in this mode)

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\../kernel_forward.h(289): warning #860-D: __declspec attributes ignored

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\../kernel_forward.h(308): warning #860-D: __declspec attributes ignored

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: expected a type specifier

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: type name is not allowed

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: expected a type specifier

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: too many arguments for class template "AttentionKernel"

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: expected a type specifier

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: type name is not allowed

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: expected a type specifier

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: too many arguments for class template "AttentionKernel"

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: expected a type specifier

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: type name is not allowed

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: expected a type specifier

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: too many arguments for class template "AttentionKernel"

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: expected a type specifier

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: type name is not allowed

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: expected a type specifier

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: too many arguments for class template "AttentionKernel"

C:\xformers\xformers\components\attention\csrc\cuda\mem_eff_attention\kernels\forward_f16_aligned.cu(3): error: no instance of function template "attention_kernel_batched" matches the specified type
```
and
```
C:\xformers\xformers\components\attention\csrc\cpu\attention.cpp(90): error C2131: expression did not evaluate to a constant
C:\xformers\xformers\components\attention\csrc\cpu\attention.cpp(90): note: failure was caused by a read of a variable outside its lifetime
C:\xformers\xformers\components\attention\csrc\cpu\attention.cpp(90): note: see usage of 'this'
C:\xformers\xformers\components\attention\csrc\cpu\attention.cpp(94): error C2668: 'std::exp': ambiguous call to overloaded function

```

**Comment by danthe3rd** [comment]
Thanks for opening this PR! It looks like it's mostly trivial errors and nothing too fundamental here.
At this point, Windows is not our priority sadly, and our dev servers are all linux - which makes it harder to ensure windows support. Would you be willing to contribute on this front?
I'd be glad to help you with anything you might need, and gladly accept PRs to either add Windows machines in the CI, fix most trivial compilation errors etc...

**Comment by C43H66N12O12S2** [comment]
I couldn't as I lack any amount of C++ or CUDA knowledge. I'm sure it is trivial, but it'd probably take me an hour to figure out what's wrong and fix it because I'm pretty much running blind here.

**Comment by danthe3rd** [comment]
Ok totally makes sense :)
Could you maybe send a PR for your changes on flash-attention here https://github.com/HazyResearch/flash-attention/tree/main ?
I have a few PRs in flight at the moment on `xformers`, I hope to land everything this week. I will try to fix the few errors you pointed after that :)

**Comment by C43H66N12O12S2** [comment]
I could but I'm not sure my "fix" would actually be an improvement 😅. My change basically amounts to completely removing std::conditional and using __half directly. Such a change would remove BF16 support, I believe.

**Comment by danthe3rd** [comment]
Oh I see ^^ Then maybe worth opening an issue with the compilation errors for the flash part at least :)

**Comment by C43H66N12O12S2** [comment]
https://github.com/HazyResearch/flash-attention/issues/50

**Comment by erip** [comment]
I can try to take the Windows fixes. If I am able to address the compiler errors, would y'all consider adding Windows to CI?

**Comment by danthe3rd** [comment]
> I can try to take the Windows fixes. If I am able to address the compiler errors, would y'all consider adding Windows to CI?

Yes that would be great! Also if you don't manage to fix all of the errors, simply adding a Windows CI can be a good start to help us iterate on that :)
For the CI, until flashattn fixes their code, we can set `XFORMERS_DISABLE_FLASH_ATTN=1` to only test xformers's own build process (https://github.com/facebookresearch/xformers/blob/main/setup.py#L72).

**Comment by EyeDeck** [comment]
https://github.com/HazyResearch/flash-attention/pull/52
Looks like it should fix Flash Attention compilation on Windows properly.

**Comment by Thomas-MMJ** [comment]
fix is committed and compiling and running flash attention works on windows.

**Comment by ifffrt** [comment]
https://www.youtube.com/watch?v=8iwBM_YB1sE

**Comment by yocabon** [comment]
Hi,
Note that I managed to compile xformers, see [the commit in my branch](https://github.com/yocabon/xformers/commit/5854be873cbc491608a77737e06135e337b4ecd1)

Some of these changes might not be necessary, as I tried different options and kept what seemed to have an impact. I didn't take notes about what error I was getting and what fixed what, so this should be redone more thoroughly.

Out of my head:
  - /Zc:lambda fixed most of the errors (and I added it last...). Got rid of the constexpr errors in templates/lambdas like [here where msvc was not happy about kMaxK](https://github.com/facebookresearch/xformers/blob/main/xformers/components/attention/csrc/cuda/mem_eff_attention/attention_backward_generic.cu#L39)

  - /Zc:preprocessor, I don't know if it's still useful. I believe it fixed a complaint [here](https://github.com/facebookresearch/xformers/blob/main/xformers/components/attention/csrc/cpu/attention.cpp#L70) - something about BLOCK not being constant at compile time, should be double checked

  - I changed `__restrict__ AccessType* grad_output_ptr` to `AccessType* __restrict__ output_ptr` ; don't know if that makes any difference but the compiler stopped complaining

  - in `epilogue_predicated_tile_iterator.h`, there was some error about the size not being correct in `asm volatile("prefetch.global.L1 [ %1 ];" : "=l"(addr) : "l"(addr));` Figured it might be because long doesn't means int64 with msvc so I changed it to uint64_t and the error went away.

  - last, I had a link error, found the solution to that [here](https://github.com/pytorch/vision/blob/main/torchvision/csrc/vision.cpp#L17)

(vs2022 build tools, cuda 11.7, pytorch 1.12.1+cu116, gpu is an rtx 2070)
```
py -3.9 .\xformers\benchmarks\benchmark_mem_eff_attention.py
```

 <details>
  <summary> Some numbers for forward</summary>

```
[----------------------- attention (attn_bias=<class 'NoneType'>) ----------------------]
                                 |  optimized[cutlass]  |  vanilla  |  optimized[flshatt]
1 threads: ------------------------------------------------------------------------------
      f16 B=16, M=4096, K=40     |         3316.8       |   7647.7  |
      f32 B=16, M=4096, K=40     |        12134.5       |  15089.5  |
      f16 B=16, M=16384, K=40    |        51953.8       |           |
      f32 B=16, M=16384, K=40    |       192166.6       |           |
      f16 B=160, M=4096, K=128   |        73016.8       |           |
      f32 B=160, M=4096, K=128   |       313499.4       |           |
      f16 B=160, M=8192, K=128   |       298440.9       |           |
      f32 B=160, M=8192, K=128   |      1260609.8       |           |
      f16 B=256, M=128, K=16     |                      |    141.6  |          34.4
      f32 B=256, M=128, K=16     |          173.4       |    265.9  |
      f16 B=256, M=128, K=32     |                      |    148.8  |          42.8
      f32 B=256, M=128, K=32     |          211.7       |    293.4  |
      f16 B=256, M=128, K=64     |                      |    186.7  |          74.3
      f32 B=256, M=128, K=64     |          280.9       |    360.2  |
      f16 B=256, M=128, K=128    |          153.2       |    246.4  |
      f32 B=256, M=128, K=128    |          553.0       |    555.3  |
      f16 B=256, M=512, K=16     |                      |   1740.9  |         316.4
      f32 B=256, M=512, K=16     |         2466.4       |   3554.2  |
      f16 B=256, M=512, K=32     |                      |   1780.4  |         431.4
      f32 B=256, M=512, K=32     |         3017.5       |   3852.2  |
      f16 B=256, M=512, K=64     |                      |   1995.3  |        1034.2
      f32 B=256, M=512, K=64     |         3992.2       |   4609.9  |
      f16 B=256, M=512, K=128    |         2000.9       |   2367.8  |
      f32 B=256, M=512, K=128    |         8132.8       |   7089.7  |
      f16 B=256, M=1024, K=16    |                      |   6863.8  |        1274.8
      f32 B=256, M=1024, K=16    |         9777.8       |  14852.2  |
      f16 B=256, M=1024, K=32    |                      |   6982.7  |        1714.8
      f32 B=256, M=1024, K=32    |        11968.6       |  15592.8  |
      f16 B=256, M=1024, K=64    |                      |   7595.7  |        4167.4
      f32 B=256, M=1024, K=64    |        15764.3       |  18555.0  |
      f16 B=256, M=1024, K=128   |         7679.7       |   8927.5  |
      f32 B=256, M=1024, K=128   |        32040.7       |  27825.9  |
      f16 B=320, M=4096, K=128   |       148386.3       |           |
      f32 B=320, M=4096, K=128   |       640185.0       |           |
      f16 B=320, M=8192, K=128   |       607208.7       |           |
      f32 B=320, M=8192, K=128   |      2560264.9       |           |
      f16 B=384, M=197, K=64     |                      |   2613.2  |         313.7
      f32 B=384, M=197, K=64     |         1385.1       |   1458.4  |
      f16 B=384, M=197, K=80     |          566.6       |   2864.5  |
      f32 B=384, M=197, K=80     |         1903.1       |   1831.9  |
      f16 B=384, M=197, K=88     |          582.5       |   3409.2  |
      f32 B=384, M=197, K=88     |         1956.4       |   1888.2  |
      f16 B=768, M=256, K=64     |                      |   1613.0  |         747.4
      f32 B=768, M=256, K=64     |         3085.2       |   3647.3  |
      f16 B=1024, M=128, K=16    |                      |    502.4  |         110.3
      f32 B=1024, M=128, K=16    |          662.7       |    999.9  |
      f16 B=1024, M=128, K=32    |                      |    548.3  |         135.7
      f32 B=1024, M=128, K=32    |          810.8       |   1109.2  |
      f16 B=1024, M=128, K=64    |                      |    667.3  |         247.6
      f32 B=1024, M=128, K=64    |         1079.3       |   1350.7  |
      f16 B=1024, M=128, K=128   |          607.1       |    890.5  |
      f32 B=1024, M=128, K=128   |         2198.6       |   2132.7  |
      f16 B=1024, M=197, K=64    |                      |   6986.9  |         802.8
      f32 B=1024, M=197, K=64    |         3701.1       |   3856.7  |
      f16 B=1024, M=197, K=80    |         1510.5       |   7615.6  |
      f32 B=1024, M=197, K=80    |         5082.4       |   4870.3  |
      f16 B=1024, M=197, K=88    |         1560.1       |   9061.1  |
      f32 B=1024, M=197, K=88    |         5219.5       |   5019.5  |
      f16 B=1024, M=512, K=16    |                      |   6978.4  |        1129.6
      f32 B=1024, M=512, K=16    |         9944.2       |  14153.6  |
      f16 B=1024, M=512, K=32    |                      |   7077.7  |        1538.7
      f32 B=1024, M=512, K=32    |        12148.7       |  15369.9  |
      f16 B=1024, M=512, K=64    |                      |   7882.4  |        3812.4
      f32 B=1024, M=512, K=64    |        16124.9       |  18372.7  |
      f16 B=1024, M=512, K=128   |         8052.5       |   9408.0  |
      f32 B=1024, M=512, K=128   |        32790.9       |  28712.7  |
      f16 B=1024, M=1024, K=16   |                      |  27548.2  |        4540.7
      f32 B=1024, M=1024, K=16   |        39402.8       |           |
      f16 B=1024, M=1024, K=32   |                      |  27767.8  |        6278.3
      f32 B=1024, M=1024, K=32   |        47950.5       |           |
      f16 B=1024, M=1024, K=64   |                      |  30457.2  |       15439.2
      f32 B=1024, M=1024, K=64   |        63403.2       |           |
      f16 B=1024, M=1024, K=128  |        30922.8       |           |
      f32 B=1024, M=1024, K=128  |       129222.5       |           |
      f16 B=2400, M=256, K=64    |                      |   4968.5  |        2272.4
      f32 B=2400, M=256, K=64    |         9628.6       |  11312.8  |
      f16 B=8192, M=82, K=64     |                      |   3357.3  |        1316.8
      f32 B=8192, M=82, K=64     |         7220.4       |   7551.5  |
```

  </details>

 <details>
  <summary> Some numbers for backward</summary>

```
[------------------ attention backward (attn_bias=<class 'NoneType'>) ------------------]
                                 |  optimized[cutlass]  |  vanilla  |  optimized[flshatt]
1 threads: ------------------------------------------------------------------------------
      f16 B=16, M=4096, K=40     |        30809.6       |  16295.8  |
      f32 B=16, M=4096, K=40     |        93904.2       |  35103.4  |
      f16 B=16, M=16384, K=40    |       487458.5       |           |
      f32 B=16, M=16384, K=40    |      1488522.2       |           |
      f16 B=160, M=4096, K=128   |       234025.3       |           |
      f32 B=160, M=4096, K=128   |      1394896.5       |           |
      f16 B=160, M=8192, K=128   |       942082.9       |           |
      f32 B=160, M=8192, K=128   |      5630896.4       |           |
      f16 B=256, M=128, K=16     |                      |    343.3  |         113.0
      f32 B=256, M=128, K=16     |          766.3       |    628.4  |
      f16 B=256, M=128, K=32     |                      |    399.5  |         161.0
      f32 B=256, M=128, K=32     |         1010.2       |    734.0  |
      f16 B=256, M=128, K=64     |                      |    515.5  |         281.1
      f32 B=256, M=128, K=64     |         1572.0       |    931.9  |
      f16 B=256, M=128, K=128    |          644.4       |    753.9  |
      f32 B=256, M=128, K=128    |         2725.6       |   1467.2  |
      f16 B=256, M=512, K=16     |                      |   4101.7  |         978.0
      f32 B=256, M=512, K=16     |        11119.5       |   8251.6  |
      f16 B=256, M=512, K=32     |                      |   4307.8  |        1431.3
      f32 B=256, M=512, K=32     |        12948.3       |   8770.5  |
      f16 B=256, M=512, K=64     |                      |   4913.2  |        2996.4
      f32 B=256, M=512, K=64     |        20450.6       |  10280.7  |
      f16 B=256, M=512, K=128    |         6761.9       |   5993.4  |
      f32 B=256, M=512, K=128    |        37111.4       |  15880.7  |
      f16 B=256, M=1024, K=16    |                      |  15821.0  |        3662.6
      f32 B=256, M=1024, K=16    |        44102.0       |  32795.6  |
      f16 B=256, M=1024, K=32    |                      |  16066.8  |        5116.0
      f32 B=256, M=1024, K=32    |        49783.8       |  38168.2  |
      f16 B=256, M=1024, K=64    |                      |  17342.4  |       11089.5
      f32 B=256, M=1024, K=64    |        77399.4       |  39509.4  |
      f16 B=256, M=1024, K=128   |        24861.7       |  20666.8  |
      f32 B=256, M=1024, K=128   |       159922.6       |  59855.9  |
      f16 B=320, M=4096, K=128   |       434147.7       |           |
      f32 B=320, M=4096, K=128   |      2717771.6       |           |
      f16 B=320, M=8192, K=128   |      1866750.3       |           |
      f16 B=384, M=197, K=64     |                      |   6851.7  |         997.9
      f32 B=384, M=197, K=64     |         7451.1       |   3213.9  |
      f16 B=384, M=197, K=80     |         2405.6       |   6812.3  |
      f32 B=384, M=197, K=80     |        10413.8       |   4366.8  |
      f16 B=384, M=197, K=88     |         2588.6       |   8693.5  |
      f32 B=384, M=197, K=88     |        11044.9       |   4490.1  |
      f16 B=768, M=256, K=64     |                      |   4208.2  |        2462.1
      f32 B=768, M=256, K=64     |        15920.5       |   8556.8  |
      f16 B=1024, M=128, K=16    |                      |   1274.2  |         432.7
      f32 B=1024, M=128, K=16    |         3729.5       |   2399.9  |
      f16 B=1024, M=128, K=32    |                      |   1480.4  |         615.5
      f32 B=1024, M=128, K=32    |         4637.9       |   2756.2  |
      f16 B=1024, M=128, K=64    |                      |   1900.2  |        1028.4
      f32 B=1024, M=128, K=64    |         7193.9       |   3518.1  |
      f16 B=1024, M=128, K=128   |         2449.0       |   2869.0  |
      f32 B=1024, M=128, K=128   |        11674.5       |   5670.7  |
      f16 B=1024, M=197, K=64    |                      |  18181.0  |        2615.0
      f32 B=1024, M=197, K=64    |        19750.5       |   8402.0  |
      f16 B=1024, M=197, K=80    |         6171.5       |  18090.2  |
      f32 B=1024, M=197, K=80    |        27708.3       |  11525.5  |
      f16 B=1024, M=197, K=88    |         6617.5       |  22219.0  |
      f32 B=1024, M=197, K=88    |        29578.0       |  11868.9  |
      f16 B=1024, M=512, K=16    |                      |  16460.6  |        3622.9
      f32 B=1024, M=512, K=16    |        42147.1       |  40719.9  |
      f16 B=1024, M=512, K=32    |                      |  17461.9  |        5343.7
      f32 B=1024, M=512, K=32    |        48243.6       |  34930.2  |
      f16 B=1024, M=512, K=64    |                      |  19470.3  |       11716.2
      f32 B=1024, M=512, K=64    |        76744.8       |  41231.2  |
      f16 B=1024, M=512, K=128   |        25303.4       |  23706.0  |
      f32 B=1024, M=512, K=128   |       141650.4       |           |
      f16 B=1024, M=1024, K=16   |                      |           |       13616.2
      f32 B=1024, M=1024, K=16   |       164181.0       |           |
      f16 B=1024, M=1024, K=32   |                      |           |       19009.8
      f32 B=1024, M=1024, K=32   |       185452.9       |           |
      f16 B=1024, M=1024, K=64   |                      |           |       44051.2
      f32 B=1024, M=1024, K=64   |       310017.0       |           |
      f16 B=1024, M=1024, K=128  |        92997.4       |           |
      f32 B=1024, M=1024, K=128  |       669412.2       |           |
      f16 B=2400, M=256, K=64    |                      |  13050.7  |        7654.7
      f32 B=2400, M=256, K=64    |        46483.0       |  26728.9  |
      f16 B=8192, M=82, K=64     |                      |   8194.0  |        5678.2
      f32 B=8192, M=82, K=64     |        48542.3       |  16888.7  |

```
  </details>

```
pytest .\tests\test_mem_eff_attention.py
[...]
6774 passed, 9702 skipped, 64 warnings in 48.41s
```

**Comment by erip** [comment]
That's huge, @yocabon!

**Comment by Thomas-MMJ** [comment]
is working here 3060 GPU 6 GB ram (laptop variant).  Will have benchmarks finished in about 20 minutes.

**Comment by Thomas-MMJ** [comment]
Couldn't complete the benchmark, failed here, most of the way through

```
====== {'shape': (160, 4096, 128), 'num_threads': 1, 'attn_bias_type': <class 'NoneType'>, 'dtype': torch.float16} ======
Traceback (most recent call last):
  File "benchmark_mem_eff_attention.py", line 280, in <module>
    benchmark_main_helper(benchmark_backward, CASES, min_run_time=min_run_time)
  File "C:\Users\username\yocoban_xformers\xformers\xformers\benchmarks\utils.py", line 365, in benchmark_main_helper
    measurement = benchmark_object.blocked_autorange(
  File "C:\Users\username\mambaforge\envs\ldm\lib\site-packages\torch\utils\benchmark\utils\timer.py", line 394, in blocked_autorange
    number = self._estimate_block_size(min_run_time)
  File "C:\Users\username\mambaforge\envs\ldm\lib\site-packages\torch\utils\benchmark\utils\timer.py", line 311, in _estimate_block_size
    time_taken = self._timeit(number)
  File "C:\Users\username\mambaforge\envs\ldm\lib\site-packages\torch\utils\benchmark\utils\timer.py", line 256, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "C:\Users\username\mambaforge\envs\ldm\lib\timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "C:\Users\username\mambaforge\envs\ldm\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\username\mambaforge\envs\ldm\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\Users\username\mambaforge\envs\ldm\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "C:\Users\username\mambaforge\envs\ldm\lib\site-packages\xformers-0.0.14.dev0-py3.8-win-amd64.egg\xformers\ops.py", line 516, in backward
    cls._flash_attn_backward(
  File "C:\Users\username\mambaforge\envs\ldm\lib\site-packages\xformers-0.0.14.dev0-py3.8-win-amd64.egg\xformers\ops.py", line 592, in _flash_attn_backward
    softmax_d = _C_flashattention.bwd(
RuntimeError: Expected is_sm80 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

**Comment by C43H66N12O12S2** [comment]
I've compiled xformers from @yocabon's fork, though example code for SD fails without errors (produces a broken image). A very similar code block reportedly works in diffusers, so I'm inclined to blame errors in compilation, though some guidance would be really welcome :)
```
import math
import torch
from torch import einsum
import xformers
import xformers.ops
from ldm.util import default
from einops import rearrange
import functorch
xformers._is_functorch_available = True
def attention(self, x, context=None, mask=None):
    h = self.heads
    d = int(self.scale ** -2)
    q = self.to_q(x)
    context = default(context, x)
    k = self.to_k(context)
    v = self.to_v(context)
    del context, x

    b, _, _ = q.shape
    q, k, v = map(
        lambda t: t.unsqueeze(3)
        .reshape(b, t.shape[1], h, d)
        .permute(0, 2, 1, 3)
        .reshape(b * h, t.shape[1], d)
        .contiguous(),
        (q, k, v),
    )

    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=xformers.ops.MemoryEfficientAttentionCutlassOp)

    out = (
        out.unsqueeze(0)
        .reshape(b, h, out.shape[1], d)
        .permute(0, 2, 1, 3)
        .reshape(b, out.shape[1], h * d)
    )

    return self.to_out(out)
```

**Comment by Thomas-MMJ** [comment]
To build check out this fork,

'git clone https://github.com/yocabon/xformers.git'

Then switch to the win_attempt branch

'cd xformers'

'git checkout -b win_attempt'

Then recursively checkout the libraries needed to build it

'git submodule update --init --recursive'

Lastly build

'python3 install requirements.txt'

'python3 setup.py build'

'python3 setup.py bdist_wheel'

and install

'pip install -e .'

**Comment by fmassa** [comment]
@yocabon that is awesome! Would you mind sending a PR with your fixes?

**Comment by 1blackbar** [comment]
So anyone installed on win and can confirm speedup with stable diffusion ?

**Comment by Thomas-MMJ** [comment]
Can confirm it works and gives speed up.  Using https://github.com/ShivamShrirao/diffusers/ - which has the change integrated by default, I get about 40% faster.

Currently trying to get it working on the SD-Automatic fork and it is not working yet. See discussion here,

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/1003

**Comment by neonsecret** [comment]
Okay guys, made a working version https://github.com/neonsecret/xformers
Also made a prebuilt wheel for python 3.9

**Comment by fmassa** [comment]
This should be fixed now thanks to the amazing work from @yocabon in https://github.com/facebookresearch/xformers/pull/460

I'm closing this issue but let us know if you face any further problems with Windows in the future
