### ISSUE TITLE
recursion error reached hipifying cutlass portion of xformers

### ISSUE THREAD

**Issue by cornpo** [facebookresearch/xformers#485]
# 🐛 Bug

hipify-python from rocm runs into a maximum recursion error. I think the problem is AMD first, then cutlass. Figured there's no harm in letting you guys know.

1. Install rocm 5.3
2. `pip install git+https://github.com/facebookresearch/xformers` or `pip install xformers`
3. Wish you'd spent the extra $600

```
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1508 lines of output]
      /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/fmha_utils.h -> /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/fmha_utils_hip.h [ok]
      /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/fmha.h -> /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/fmha_hip.h [ok]
      /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/fmha_api.cpp -> /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/fmha_api_hip.cpp [ok]
      /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/static_switch.h -> /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/static_switch.h [skipped, no changes]
      /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/fp16_switch.h -> /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/fp16_switch.h [skipped, no changes]
      /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/philox.cuh -> /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/philox.cuh [skipped, no changes]
      /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/fmha/utils.h -> /tmp/pip-req-build-r9do6iix/third_party/flash-attention/csrc/flash_attn/src/fmha/utils_hip.h [ok]
      /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/cutlass.h -> /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/cutlass.h [skipped, no changes]
      /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/platform/platform.h -> /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/platform/platform.h [skipped, no changes]
      /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/integer_subbyte.h -> /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/integer_subbyte.h [skipped, no changes]
      /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/half.h -> /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/half_hip.h [ok]
      /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/bfloat16.h -> /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/bfloat16.h [skipped, no changes]
      /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/tfloat32.h -> /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/tfloat32.h [skipped, no changes]
      /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/numeric_types.h -> /tmp/pip-req-build-r9do6iix/third_party/cutlass/include/cutlass/numeric_types_hip.h [ok]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-r9do6iix/setup.py", line 258, in <module>
          ext_modules=get_extensions(),
        File "/tmp/pip-req-build-r9do6iix/setup.py", line 214, in get_extensions
          ext_modules += get_flash_attention_extensions(
        File "/tmp/pip-req-build-r9do6iix/setup.py", line 108, in get_flash_attention_extensions
          CUDAExtension(
        File "/home/cornpop/conda/envs/shit/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1010, in CUDAExtension
          hipify_result = hipify_python.hipify(
        File "/home/cornpop/conda/envs/shit/lib/python3.9/site-packages/torch/utils/hipify/hipify_python.py", line 1042, in hipify
          preprocess_file_and_save_result(output_directory, filepath, all_files, header_include_dirs,
        File "/home/cornpop/conda/envs/shit/lib/python3.9/site-packages/torch/utils/hipify/hipify_python.py", line 176, in preprocess_file_and_save_result
          result = preprocessor(output_directory, filepath, all_files, header_include_dirs, stats,
        File "/home/cornpop/conda/envs/shit/lib/python3.9/site-packages/torch/utils/hipify/hipify_python.py", line 829, in preprocessor
          output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
        File "/home/cornpop/conda/envs/shit/lib/python3.9/site-packages/torch/utils/hipify/hipify_python.py", line 819, in repl
```
Then it repeats hipify_python.py until pythons recursion limit is exceeded.

## Expected behavior

xformers to begin xforming (or whatever it does) when it compiles.

## Environment

PyTorch version: 1.12.1+rocm5.1.1
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.1.20531-cacfa990

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.23.1
Libc version: glibc-2.35

Python version: 3.9.13 (main, Oct 13 2022, 21:15:33)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration: AMD Radeon RX 6800 XT
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.1.20531
MIOpen runtime version: 2.16.0
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] clip-anytorch==2.5.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] pytorch-benchmark==0.3.4
[pip3] pytorch-lightning==1.7.7
[pip3] torch==1.12.1+rocm5.1.1
[pip3] torch-ort==1.12.0
[pip3] torchaudio==0.12.1+rocm5.1.1
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.10.0
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+rocm5.1.1
[conda] clip-anytorch             2.5.0                    pypi_0    pypi
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] pytorch-benchmark         0.3.4                    pypi_0    pypi
[conda] pytorch-lightning         1.7.7                    pypi_0    pypi
[conda] torch                     1.12.1+rocm5.1.1          pypi_0    pypi
[conda] torch-ort                 1.12.0                   pypi_0    pypi
[conda] torchaudio                0.12.1+rocm5.1.1          pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              0.10.0                   pypi_0    pypi
[conda] torchtext                 0.13.1                   pypi_0    pypi
[conda] torchvision               0.13.1+rocm5.1.1          pypi_0    pypi

https://github.com/ROCm-Developer-Tools/HIPIFY/issues/660

**Comment by fmassa** [comment]
Hey,

Thanks for letting us know. Keep us updated whenever xformers work with hipify!

**Comment by hwu36** [comment]
FYI, it is waste of time to hipify cutlass since cutlass uses lots of inline ptx.  You could rewrite these inline ptx in cuda, but it is not cutlass anymore.

**Comment by cornpo** [comment]
ptx->llvm

I'll be back in 3 years. Lol.

**Comment by luise1030** [comment]
Just want to share my runs:

With the docker image **rocm/pytorch:rocm5.5_ubuntu20.04_py3.8_pytorch_2.0.0_preview**, I can install xformers properly but fail in some cases of xformers/tests

python3 -m pip install git+https://github.com/facebookresearch/xformers 2>&1 |tee r_ins_xformers.log
Collecting git+https://github.com/facebookresearch/xformers
  Cloning https://github.com/facebookresearch/xformers to /tmp/pip-req-build-57msi0v0
  Running command git clone -q https://github.com/facebookresearch/xformers /tmp/pip-req-build-57msi0v0
  Running command git submodule update --init --recursive -q
Requirement already satisfied: torch>=1.12 in /opt/conda/envs/py_3.8/lib/python3.8/site-packages (from xformers==0.0.21+7633838.d20230627) (2.0.1+gitcb3d1d0)
Requirement already satisfied: numpy in /opt/conda/envs/py_3.8/lib/python3.8/site-packages (from xformers==0.0.21+7633838.d20230627) (1.18.5)
Requirement already satisfied: jinja2 in /opt/conda/envs/py_3.8/lib/python3.8/site-packages/Jinja2-3.1.2-py3.8.egg (from torch>=1.12->xformers==0.0.21+7633838.d20230627) (3.1.2)
Requirement already satisfied: filelock in /opt/conda/envs/py_3.8/lib/python3.8/site-packages/filelock-3.12.0-py3.8.egg (from torch>=1.12->xformers==0.0.21+7633838.d20230627) (3.12.0)
Requirement already satisfied: sympy in /opt/conda/envs/py_3.8/lib/python3.8/site-packages (from torch>=1.12->xformers==0.0.21+7633838.d20230627) (1.12)
Requirement already satisfied: typing-extensions in /opt/conda/envs/py_3.8/lib/python3.8/site-packages (from torch>=1.12->xformers==0.0.21+7633838.d20230627) (4.5.0)
Requirement already satisfied: pytorch-triton-rocm<2.1,>=2.0.0 in /opt/conda/envs/py_3.8/lib/python3.8/site-packages/pytorch_triton_rocm-2.0.2-py3.8-linux-x86_64.egg (from torch>=1.12->xformers==0.0.21+7633838.d20230627) (2.0.2)
Requirement already satisfied: networkx in /opt/conda/envs/py_3.8/lib/python3.8/site-packages (from torch>=1.12->xformers==0.0.21+7633838.d20230627) (2.6.3)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/envs/py_3.8/lib/python3.8/site-packages (from jinja2->torch>=1.12->xformers==0.0.21+7633838.d20230627) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/envs/py_3.8/lib/python3.8/site-packages (from sympy->torch>=1.12->xformers==0.0.21+7633838.d20230627) (1.3.0)
Requirement already satisfied: cmake in /opt/conda/envs/py_3.8/lib/python3.8/site-packages/cmake-3.26.3-py3.8-linux-x86_64.egg (from pytorch-triton-rocm<2.1,>=2.0.0->torch>=1.12->xformers==0.0.21+7633838.d20230627) (3.26.3)
Requirement already satisfied: lit in /opt/conda/envs/py_3.8/lib/python3.8/site-packages/lit-16.0.3-py3.8.egg (from pytorch-triton-rocm<2.1,>=2.0.0->torch>=1.12->xformers==0.0.21+7633838.d20230627) (16.0.3)
Building wheels for collected packages: xformers
  Building wheel for xformers (setup.py): started
  Building wheel for xformers (setup.py): finished with status 'done'
  Created wheel for xformers: filename=xformers-0.0.21+7633838.d20230627-cp38-cp38-linux_x86_64.whl size=12052709 sha256=60b1eb235b61e03bf09faca3402650ebfb8d674f2a15d8c78145df45f690b693
  Stored in directory: /tmp/pip-ephem-wheel-cache-uwgqvroc/wheels/de/e4/c2/1e72d8f225bae673b80011d18ad49a13e96391d308848b5c9f
Successfully built xformers
Installing collected packages: xformers
Successfully installed xformers-0.0.21+7633838.d20230627
WARNING: You are using pip version 20.1.1; however, version 23.1.2 is available.
