### ISSUE TITLE
triton layernorm problem

### ISSUE THREAD

**Issue by hoangmit** [facebookresearch/xformers#519]
# 🐛 Bug
```
Traceback (most recent call last):
  File "...#link-tree/xformers/triton/layer_norm.py", line 67, in layer_norm
    return _LayerNorm.apply(x, weight, bias, eps)
  File "...#link-tree/torch/cuda/amp/autocast_mode.py", line 99, in decorate_fwd
    return fwd(*args, **kwargs)
  File "...#link-tree/xformers/triton/k_layer_norm.py", line 291, in forward
    _layer_norm_fw[(M,)](
  File "...#link-tree/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
TypeError: _layer_norm_fw() got an unexpected keyword argument 'BLOCK_SIZE_N'
```

.....
```
  File "...#link-tree/torch/nn/modules/module.py", line 1423, in _call_impl
    return forward_call(*input, **kwargs)
  File "...#link-tree/xformers/components/residual.py", line 88, in forward
    return self.norm(x)
  File "...#link-tree/torch/nn/modules/module.py", line 1423, in _call_impl
    return forward_call(*input, **kwargs)
  File "...#link-tree/xformers/triton/layer_norm.py", line 45, in forward
    return layer_norm(x, self.weight, self.bias, self.epsilon)
  File "...#link-tree/xformers/triton/layer_norm.py", line 68, in layer_norm
    except (triton.code_gen.OutOfResources, RuntimeError) as e:
AttributeError: module 'triton' has no attribute 'code_gen'
```

## To Reproduce
```
attention_config = {
    "name": "favor",
    "dropout": dropout,
}

dec_config = xFormerDecoderConfig(
    dim_model=embedding_dim,
    multi_head_config_masked={
        "num_heads": num_heads,
        "residual_dropout": 0,
        "attention": attention_config,
    },
    multi_head_config_cross={
        "num_heads": num_heads,
        "residual_dropout": 0,
        "attention": attention_config.copy(),
    },
    feedforward_config={
        "name": "MLP",
        "dropout": dropout,
        "activation": "gelu",
        "hidden_layer_multiplier": 4,
    },
    layer_norm_style="post",
    use_triton=True,
)
```

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

- PyTorch Version (e.g., 1.0): master
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source): fbcode
- Build command you used (if compiling from source): buck build //...
- Python version: 3.9
- CUDA/cuDNN version: 11.4
- GPU models and configuration: V100
- Any other relevant information:

**Comment by danthe3rd** [comment]
Hi,
Can you report which version of triton you are using?
Thanks

**Comment by danthe3rd** [comment]
Might be fixed with this pull-request: https://github.com/facebookresearch/xformers/pull/483

**Comment by hoangmit** [comment]
Triton version

triton.__version__
'2.0.0'

**Comment by danthe3rd** [comment]
Oh didn't see you were using it in fbcode. It might be specific to the fbcode setup.
Can you post on our [(Meta-internal) group](https://fb.workplace.com/groups/252292133202810)? We've never tried xFormers in fbcode (didn't even know it was there) - so there might be some work needed to get it to work properly (there are also some dependencies on triton version)
