### ISSUE TITLE
Following install instructions, got Filename too long error, then compilation errors VS related

### ISSUE THREAD

**Issue by Pirog17000** [facebookresearch/xformers#531]
# ❓ Questions and Help

So, following the instructions given on the main page, 

```
# (Optional) Makes the build much faster
pip install ninja
# Set TORCH_CUDA_ARCH_LIST if running and building on different GPU types
pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
```

**but have this log at the end:**
```

  Updating files:  97% (610/628)
  Updating files:  98% (616/628)
  Updating files:  99% (622/628)
  Updating files: 100% (628/628)
  Updating files: 100% (628/628), done.
  Running command git show-ref main
  efdca026381a13319be082f079c60275cc871301 refs/heads/main
  efdca026381a13319be082f079c60275cc871301 refs/remotes/origin/main
  Running command git symbolic-ref -q HEAD
  refs/heads/main
  Resolved https://github.com/facebookresearch/xformers.git to commit efdca026381a13319be082f079c60275cc871301
  Running command git submodule update --init --recursive -q
  error: unable to create file docs/classcutlass_1_1epilogue_1_1thread_1_1LinearCombinationRelu_3_01ElementOutput___00_01Count_00_014d4e40c4295be6a8d8778d86e94fe14a.html: Filename too long
  error: unable to create file docs/classcutlass_1_1epilogue_1_1thread_1_1LinearCombinationRelu_3_01ElementOutput___00_01Count_00_01int_00_01float_00_01Round_01_4.html: Filename too long
  error: unable to create file docs/classcutlass_1_1epilogue_1_1warp_1_1FragmentIteratorComplexTensorOp_3_01WarpShape___00_01Operato65e8dd1d709c1257fe4e30825dcc5f06.html: Filename too long
  error: unable to create file docs/classcutlass_1_1epilogue_1_1warp_1_1FragmentIteratorComplexTensorOp_3_01WarpShape___00_01Operato8cf03c624cf3210c71b7cbd580b080f8.html: Filename too long
  error: unable to create file docs/classcutlass_1_1epilogue_1_1warp_1_1FragmentIteratorSimt_3_01WarpShape___00_01Operator___00_01la3f2abc523201c1b0228df99119ab88e1.html: Filename too long
  error: unable to create file docs/classcutlass_1_1epilogue_1_1warp_1_1FragmentIteratorSimt_3_01WarpShape___00_01Operator___00_01la91754875457d1736401ce8b815f5a9ea.html: Filename too long
  error: unable to create file 
. . .
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileAccessIterator_3_01Shape___00_01Element_0a9491607d11be8e1780e79ad711aa42.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileAccessIterator_3_01Shape___00_01Element_159afb0a42935c95137b94a812a0c347.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileAccessIterator_3_01Shape___00_01Element_3be8b96d170d886f39b6b30acab65e7a.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileAccessIterator_3_01Shape___00_01Element_7fe4ae214b926456132d144640afba71.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_0156743786c2e07a4e523ad410e291265.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_02d305cfb0b55c6fb236a52cf2240651e.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_032f88d1be8b209e44a4815c707ba35bb.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_0390833403016f5d817416e20828845df.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_039093927f4b1ee61538c569bf1ae4efd.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_05192e46ead3e35a0208870cfc60f5da5.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_052caec9d5bceeb59b9a13cb3338ce64d.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_06b6dd3317cd1748fb948900df8beec57.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_078e1f4b2964afcce5387420c9c8eaea8.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_0bc37beaa523707a55987f4ffcc372fcd.html: Filename too long
  fatal: Unable to checkout '319a389f42b776fae5701afcb943fc03be5b5c25' in submodule path 'third_party/flash-attention/csrc/flash_attn/cutlass'
  fatal: Failed to recurse into submodule path 'third_party/flash-attention'
  error: subprocess-exited-with-error

  git submodule update --init --recursive -q did not run successfully.
  exit code: 1

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: git submodule update --init --recursive -q
  cwd: C:\Windows\Temp\pip-install-41neinzo\xformers_360dda9894394700b2ff49e641a78998
error: subprocess-exited-with-error

git submodule update --init --recursive -q did not run successfully.

```

This is a windows system and I'm using a pip way of installing xformers.
help! :)

**Comment by bottler** [comment]
I think you are hitting a windows error on the length of a path. Can you check out this repo to a location of your own whose path is much shorter than `C:\Windows\Temp\pip-install-41neinzo\xformers_360dda9894394700b2ff49e641a78998` ?  
if so  you could then use `pip install .`.

**Comment by Pirog17000** [comment]
And it failed again. (or it's me, I'm not doing this type of things regularly) @bottler 
```
git init
git pull https://github.com/facebookresearch/xformers.git
git submodule update --init --recursive
pip install .
```
Results into this:
```
 ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1900, in _run_ninja_build
      subprocess.run(
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "B:\1\setup.py", line 264, in <module>
      setuptools.setup(
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 61, in run
      return orig.install.run(self)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\command\install.py", line 568, in run
      self.run_command('build')
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
      build_ext.build_extensions(self)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 529, in build_extension
      objects = self.compiler.compile(sources,
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
      _write_ninja_file_and_compile_objects(
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
      _run_ninja_build(
    File "C:\Users\Mike\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1916, in _run_ninja_build
      raise RuntimeError(message) from e
  RuntimeError: Error compiling objects for extension
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

xformers

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by Pirog17000** [comment]
And more after uninstalling ninja:

```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include\crt/host_config.h(160): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  fmha_block_dgrad_fp16_kernel_loop.sm80.cu
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.1\\bin\\nvcc.exe' failed with exit code 2
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
```
Interesting, so it will require **SPECIFIC** Visual Studio. Not mentioned anywhere.

**Comment by danthe3rd** [comment]
Oh that's a specific requirement from CUDA.
Each CUDA version supports a specific version of compilers.
You have a fairly old version of CUDA (11.1) and should probably use a newer version. In fact, PyTorch 1.13 binaries (if you install with pip/conda) are provided for CUDA 11.6 and 11.7 - and you should build xFormers with the same CUDA version as the one in pytorch (try `python -c "import torch; print(torch.version.cuda)"`)

**Comment by Pirog17000** [comment]
I have updated Cuda to 11.8, now it builds.. will report if this thing will succeed. So far it works, thanks for the tip!
```
Building wheels for collected packages: xformers
  Building wheel for xformers (setup.py): started
  Building wheel for xformers (setup.py): still running...
  Building wheel for xformers (setup.py): still running...
  Building wheel for xformers (setup.py): still running...
  Building wheel for xformers (setup.py): still running...
  Building wheel for xformers (setup.py): still running...
```

**Comment by Pirog17000** [comment]
```
  Building wheel for xformers (setup.py): still running...
  Building wheel for xformers (setup.py): finished with status 'done'
  Created wheel for xformers: filename=xformers-0.0.15.dev0+c101579.d20221117-cp310-cp310-win_amd64.whl size=93318166 sha256=e63de512de849f2c2253b8d02eb5b8417669d35bff5a32fcbf57376105e34efb
  Stored in directory: C:\Windows\Temp\pip-ephem-wheel-cache-2wffttv_\wheels\8c\cb\63\a6c45e2b9fb3769c9a9f6e71d7a071237071096bc962f199c5
Successfully built xformers
Installing collected packages: xformers
Successfully installed xformers-0.0.15.dev0+c101579.d20221117
```
