### ISSUE TITLE
Building blocksparse kernels

### ISSUE THREAD

**Issue by domluna** [facebookresearch/xformers#60]
# ❓ Questions and Help

It looks like sputnik kernels are not built when running the setup script.

I build the source with

```sh
λ ~/dev/xformers: python setup.py build develop
```

I get the following error

```sh
λ ~/dev/xformers: python xformers/benchmarks/benchmark_triton_blocksparse.py
WARNING:root:Unsupported device, Triton code generation may fail
M=128, N=128, K=128 - pytorch - sdd - 16:  - 0.12TFlops
Traceback (most recent call last):
  File "/home/domluna/dev/xformers/xformers/benchmarks/benchmark_triton_blocksparse.py", line 142, in <module>
    bench_matmul(torch.float16, shapes)
  File "/home/domluna/dev/xformers/xformers/benchmarks/benchmark_triton_blocksparse.py", line 116, in bench_matmul
    ms = triton.testing.do_bench(lambda: testcase.function())[0]
  File "/home/domluna/anaconda3/lib/python3.9/site-packages/triton/testing.py", line 131, in do_bench
    fn()
  File "/home/domluna/dev/xformers/xformers/benchmarks/benchmark_triton_blocksparse.py", line 116, in <lambda>
    ms = triton.testing.do_bench(lambda: testcase.function())[0]
  File "/home/domluna/dev/xformers/xformers/benchmarks/benchmark_triton_blocksparse.py", line 97, in sparse_step
    return _matmul_with_mask(a_cs, b_cs, sparse_cs_mask)
  File "/home/domluna/dev/xformers/xformers/components/attention/core.py", line 79, in _matmul_with_mask
    return mask.matmul_with_mask(a, b)
  File "/home/domluna/dev/xformers/xformers/components/attention/_sputnik_sparse.py", line 255, in matmul_with_mask
    out = _sddmm.apply(
  File "/home/domluna/dev/xformers/xformers/components/attention/_sputnik_sparse.py", line 94, in forward
    out = _sddmm_func(a, b, row_indices, row_offsets, column_indices)
  File "/home/domluna/dev/xformers/xformers/components/attention/_sputnik_sparse.py", line 61, in _sddmm_func
    return torch.ops.xformers.sddmm_sputnik(
NotImplementedError: Could not run 'xformers::sddmm_sputnik' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'xformers::sddmm_sputnik' is only available for these backends: [CPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

CPU: registered at /home/domluna/dev/xformers/xformers/components/attention/csrc/cpu/sddmm.cpp:100 [kernel]
BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ADInplaceOrView: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/VariableFallbackKernel.cpp:35 [backend fallback]
AutogradCPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/VariableFallbackKernel.cpp:39 [backend fallback]
AutogradCUDA: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/VariableFallbackKernel.cpp:47 [backend fallback]
AutogradXLA: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/VariableFallbackKernel.cpp:51 [backend fallback]
AutogradLazy: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/VariableFallbackKernel.cpp:55 [backend fallback]
AutogradXPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/VariableFallbackKernel.cpp:43 [backend fallback]
AutogradMLC: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/core/VariableFallbackKernel.cpp:59 [backend fallback]
Tracer: registered at /opt/conda/conda-bld/pytorch_1634272204863/work/torch/csrc/autograd/TraceTypeManual.cpp:291 [backend fallback]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/autocast_mode.cpp:466 [backend fallback]
Autocast: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/autocast_mode.cpp:305 [backend fallback]
Batched: registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
```

Even though there's the warning about code generation possibly failing it seems to work fine when the ops are not sparse. Triton kernels showing improvements:

```sh
λ ~/dev/xformers: python xformers/benchmarks/benchmark_triton_softmax.py
WARNING:root:Unsupported device, Triton code generation may fail
 ------------- Type: torch.float16 -------------
| Units: GB/s                                    |B=8, M=384, K=128   |B=8, M=784, K=512   |B=4, M=1024, K=768  |B=4, M=2048, K=1024 |B=2, M=2048, K=2048 |B=2, M=2048, K=4096 |B=2, M=4096, K=4096 |B=1, M=2048, K=12288|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|pytorch - fw                                    |178.7               |332.6               |293.2               |335.9               |303.5               |314.1               |319.1               |307.0               |
|triton - fw                                     |136.5               |348.4               |343.1               |374.8               |374.0               |380.3               |385.5               |378.1               |
|triton - causal - fw                            |128.0               |328.5               |339.9               |364.1               |327.0               |390.1               |411.7               |360.4               |
|pytorch - log - fw                              |195.8               |348.4               |337.5               |367.1               |365.7               |376.6               |383.3               |351.4               |
|triton - log - fw                               |150.3               |351.2               |352.3               |375.0               |376.5               |381.9               |386.4               |381.0               |

QApplication: invalid style override passed, ignoring it.
 ------------- Type: torch.float32 -------------
| Units: GB/s                                    |B=8, M=384, K=128   |B=8, M=784, K=512   |B=4, M=1024, K=768  |B=4, M=2048, K=1024 |B=2, M=2048, K=2048 |B=2, M=2048, K=4096 |B=2, M=4096, K=4096 |B=1, M=2048, K=12288|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|pytorch - fw                                    |307.2               |361.1               |364.9               |368.2               |368.1               |372.4               |379.0               |246.4               |
|triton - fw                                     |265.7               |371.0               |374.5               |383.8               |381.4               |387.8               |385.2               |379.7               |
|triton - causal - fw                            |256.0               |417.0               |438.1               |427.2               |479.3               |586.7               |492.8               |646.7               |
|pytorch - log - fw                              |310.1               |364.3               |366.6               |366.3               |379.4               |382.4               |386.8               |219.1               |
|triton - log - fw                               |275.4               |371.8               |377.4               |384.6               |381.4               |387.8               |385.5               |379.6               |

 ------------- Type: torch.float16 -------------
| Units: GB/s                                    |B=8, M=384, K=128   |B=8, M=784, K=512   |B=4, M=1024, K=768  |B=4, M=2048, K=1024 |B=2, M=2048, K=2048 |B=2, M=2048, K=4096 |B=2, M=4096, K=4096 |B=1, M=2048, K=12288|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|pytorch - fw+bw                                 |77.2                |100.4               |98.3                |106.6               |104.0               |106.9               |108.4               |105.0               |
|triton - fw+bw                                  |73.8                |128.2               |127.6               |136.6               |136.6               |139.7               |142.2               |140.8               |
|triton - causal - fw+bw                         |72.9                |131.8               |132.1               |141.2               |143.7               |159.9               |156.8               |156.7               |
|pytorch - log - fw+bw                           |85.3                |125.4               |124.1               |135.8               |134.1               |138.6               |140.8               |134.3               |
|triton - log - fw+bw                            |75.9                |128.4               |127.9               |136.5               |136.6               |140.0               |142.3               |140.8               |

 ------------- Type: torch.float32 -------------
| Units: GB/s                                    |B=8, M=384, K=128   |B=8, M=784, K=512   |B=4, M=1024, K=768  |B=4, M=2048, K=1024 |B=2, M=2048, K=2048 |B=2, M=2048, K=4096 |B=2, M=4096, K=4096 |B=1, M=2048, K=12288|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|pytorch - fw+bw                                 |126.4               |107.0               |106.8               |110.3               |109.8               |110.8               |111.8               |98.0                |
|triton - fw+bw                                  |130.8               |136.3               |135.7               |141.1               |140.9               |142.5               |142.9               |125.7               |
|triton - causal - fw+bw                         |128.8               |146.2               |147.4               |149.9               |159.9               |174.9               |162.4               |54.1                |
|pytorch - log - fw+bw                           |145.1               |134.9               |134.5               |139.4               |139.4               |141.1               |142.1               |116.7               |
|triton - log - fw+bw                            |132.0               |136.4               |135.8               |141.1               |140.9               |142.4               |142.8               |125.2               |

```

**Comment by blefaudeux** [comment]
It's mentioned in the README, probably not easy enough to follow but the sparse kernels (not blocksparse, there's some confusion here as blocksparse comes from Triton) are build during setup if it manages its way around the exposed CUDA toolchain.

Could you post the `python setup.py build develop` log (after you wipe the /build folder) ? could you report some more info on your pytorch install, your cuda install and nvcc version ? It's really hard to debug with the information present here

**Comment by domluna** [comment]
The issue seemed to be that the cuda toolkit installed with pytorch doesn't have nvcc, installing the latest cuda seems to have fixed this
