### ISSUE TITLE
Building from source on Windows failed: 'E:/PyCharmProjects/xformers/third_party/flash-attention/csrc/flash_attn/src/fmha_bwd_hdim128.cu', needed by 'E:/PyCharmProjects/xformers/build/temp.win-amd64-cpython-39/Release/PyCharmProjects/xformers/third_party/flash-attention/csrc/flash_attn/src/fmha_bwd_hdim128.obj', missing and no known rule to make it

### ISSUE THREAD

**Issue by aliencaocao** [facebookresearch/xformers#608]
# 🐛 Bug

## Command
`python setup.py build`
1. Clone this repo
2. Run `python setup.py build`
```
E:\PyCharmProjects\xformers>python setup.py build
running build
running build_py
copying xformers\version.py -> build\lib.win-amd64-cpython-39\xformers
running build_ext
C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py:361: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py:390: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.7). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'xformers._C_flashattention' extension
Emitting ninja build file E:\PyCharmProjects\xformers\build\temp.win-amd64-cpython-39\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: 'E:/PyCharmProjects/xformers/third_party/flash-attention/csrc/flash_attn/src/fmha_bwd_hdim128.cu', needed by 'E:/PyCharmProjects/xformers/build/temp.win-amd64-cpython-39/Release/PyCharmProjects/xformers/third_party/flash-attention/csrc/flash_attn/src/fmha_bwd_hdim128.obj', missing and no known rule to make it
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 1890, in _run_ninja_build
    subprocess.run(
  File "C:\Program Files\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\PyCharmProjects\xformers\setup.py", line 301, in <module>
    setuptools.setup(
  File "C:\Program Files\Python39\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python39\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Program Files\Python39\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 845, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Program Files\Python39\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 549, in build_extension
    objects = self.compiler.compile(
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 817, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 1571, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 1906, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

- PyTorch Version (e.g., 1.0): Happens on both 1.13.1 stable and 2.0 nightly (20221219dev), both are cu117 wheels but minor version diff should not be issue since it worked in former 0.14.0
- OS (e.g., Linux): Windows 10
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.9.13
- CUDA/cuDNN version: 11.8/8.7.0
- GPU models and configuration: RTX 3080Ti
- Any other relevant information: This is introduced in 4601d9d0af4f22a7ff1e0acc5c9b2b7fd3a3ba95, building on 1 commit earlier (3714f7825fb98a57a5bfb747d9854d6b3f1d1fea) is working.

**Comment by aliencaocao** [comment]
My bad, did not update the submodules.
