### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by aliencaocao** [facebookresearch/xformers#609]
# 🐛 Bug
## To Reproduce
1. `python setup.py build`
```
E:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn\src\fmha_fwd_hdim32.cu(8): error: expected an expression

E:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn\src\fmha_fwd_hdim32.cu(8): error: expected an expression

C:/Program Files/Python39/lib/site-packages/torch/include\c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
(61): here
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
C:/Program Files/Python39/lib/site-packages/torch/include\c10/core/TensorImpl.h(77): here

C:/Program Files/Python39/lib/site-packages/torch/include\c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=true, <unnamed>=0]"
(61): here
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=true, <unnamed>=0]"
C:/Program Files/Python39/lib/site-packages/torch/include\c10/core/TensorImpl.h(2454): here
            instantiation of "__nv_bool c10::TensorImpl::SetDimsTemplate(c10::ArrayRef<T>) [with T=int64_t, <unnamed>=void]"
C:/Program Files/Python39/lib/site-packages/torch/include\c10/core/TensorImpl.h(2464): here

2 errors detected in the compilation of "E:/PyCharmProjects/xformers/third_party/flash-attention/csrc/flash_attn/src/fmha_fwd_hdim32.cu".
[6/6] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependency-output E:\PyCharmProjects\xformers\build\temp.win-amd64-cpython-39\Release\PyCharmProjects\xformers\third_party\flash-attention\csrc/flash_attn/src/fmha_fwd_hdim64.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IE:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn -IE:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn\src -IE:\PyCharmProjects\xformers\third_party\cutlass\include "-IC:\Program Files\Python39\lib\site-packages\torch\include" "-IC:\Program Files\Python39\lib\site-packages\torch\include\torch\csrc\api\include" "-IC:\Program Files\Python39\lib\site-packages\torch\include\TH" "-IC:\Program Files\Python39\lib\site-packages\torch\include\THC" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" "-IC:\Program Files\Python39\include" "-IC:\Program Files\Python39\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" -c E:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn\src\fmha_fwd_hdim64.cu -o E:\PyCharmProjects\xformers\build\temp.win-amd64-cpython-39\Release\PyCharmProjects\xformers\third_party\flash-attention\csrc/flash_attn/src/fmha_fwd_hdim64.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DHAS_PYTORCH --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --extended-lambda --generate-line-info -DNDEBUG --threads 4 --ptxas-options=-v -std=c++17 -Xcompiler /Zc:lambda -Xcompiler /Zc:preprocessor -O3 --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -std=c++17 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 --generate-line-info -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C_flashattention -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: E:/PyCharmProjects/xformers/build/temp.win-amd64-cpython-39/Release/PyCharmProjects/xformers/third_party/flash-attention/csrc/flash_attn/src/fmha_fwd_hdim64.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependency-output E:\PyCharmProjects\xformers\build\temp.win-amd64-cpython-39\Release\PyCharmProjects\xformers\third_party\flash-attention\csrc/flash_attn/src/fmha_fwd_hdim64.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IE:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn -IE:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn\src -IE:\PyCharmProjects\xformers\third_party\cutlass\include "-IC:\Program Files\Python39\lib\site-packages\torch\include" "-IC:\Program Files\Python39\lib\site-packages\torch\include\torch\csrc\api\include" "-IC:\Program Files\Python39\lib\site-packages\torch\include\TH" "-IC:\Program Files\Python39\lib\site-packages\torch\include\THC" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" "-IC:\Program Files\Python39\include" "-IC:\Program Files\Python39\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" -c E:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn\src\fmha_fwd_hdim64.cu -o E:\PyCharmProjects\xformers\build\temp.win-amd64-cpython-39\Release\PyCharmProjects\xformers\third_party\flash-attention\csrc/flash_attn/src/fmha_fwd_hdim64.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DHAS_PYTORCH --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --extended-lambda --generate-line-info -DNDEBUG --threads 4 --ptxas-options=-v -std=c++17 -Xcompiler /Zc:lambda -Xcompiler /Zc:preprocessor -O3 --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -std=c++17 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 --generate-line-info -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C_flashattention -D_GLIBCXX_USE_CXX11_ABI=0
fmha_fwd_hdim64.cu
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
fmha_fwd_hdim64.cu
C:/Program Files/Python39/lib/site-packages/torch/include\c10/macros/Macros.h(138): warning C4067: 预处理器指令后有意外 标记 - 应输入换行符
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
fmha_fwd_hdim64.cu
C:/Program Files/Python39/lib/site-packages/torch/include\c10/macros/Macros.h(138): warning C4067: 预处理器指令后有意外 标记 - 应输入换行符
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
fmha_fwd_hdim64.cu
C:/Program Files/Python39/lib/site-packages/torch/include\c10/macros/Macros.h(138): warning C4067: 预处理器指令后有意外 标记 - 应输入换行符
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
fmha_fwd_hdim64.cu
C:/Program Files/Python39/lib/site-packages/torch/include\c10/macros/Macros.h(138): warning C4067: 预处理器指令后有意外 标记 - 应输入换行符
C:/Program Files/Python39/lib/site-packages/torch/include\c10/cuda/CUDAStream.h(119): warning #177-D: variable "__err" was declared but never referenced

E:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn\src\fmha_fwd_hdim64.cu(8): error: expected an expression

E:\PyCharmProjects\xformers\third_party\flash-attention\csrc\flash_attn\src\fmha_fwd_hdim64.cu(8): error: expected an expression

C:/Program Files/Python39/lib/site-packages/torch/include\c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
(61): here
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
C:/Program Files/Python39/lib/site-packages/torch/include\c10/core/TensorImpl.h(77): here

C:/Program Files/Python39/lib/site-packages/torch/include\c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=true, <unnamed>=0]"
(61): here
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=true, <unnamed>=0]"
C:/Program Files/Python39/lib/site-packages/torch/include\c10/core/TensorImpl.h(2454): here
            instantiation of "__nv_bool c10::TensorImpl::SetDimsTemplate(c10::ArrayRef<T>) [with T=int64_t, <unnamed>=void]"
C:/Program Files/Python39/lib/site-packages/torch/include\c10/core/TensorImpl.h(2464): here

2 errors detected in the compilation of "E:/PyCharmProjects/xformers/third_party/flash-attention/csrc/flash_attn/src/fmha_fwd_hdim64.cu".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 1890, in _run_ninja_build
    subprocess.run(
  File "C:\Program Files\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\PyCharmProjects\xformers\setup.py", line 301, in <module>
    setuptools.setup(
  File "C:\Program Files\Python39\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python39\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
    self.run_command("build")
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python39\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Program Files\Python39\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 845, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Program Files\Python39\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 549, in build_extension
    objects = self.compiler.compile(
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 817, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 1571, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 1906, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

- PyTorch Version (e.g., 1.0): 2.0.0.dev20221219+cu117, happens on 1.13.1+cu117, 1.13.0+cu117 too
- OS (e.g., Linux): Windows 10
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.9.13
- CUDA/cuDNN version: 11.8/8.7.0
- GPU models and configuration: RTX 3080Ti

**Comment by aliencaocao** [comment]
Did a fresh pull and issue resolved itself.
