### ISSUE TITLE
Building xformers with LTO?

### ISSUE THREAD

**Issue by brucethemoose** [facebookresearch/xformers#652]
# 🚀 Feature

Build xformers with nvcc lto  for a potential speed boost.

The motivation is simple... more speed!

## Additional context
Adding `NVCC_APPEND_FLAGS="--gpu-architecture=lto_75 --gpu-code=lto_75 --device-c` to the environment (on Arch Linux, CUDA 11.8, Pytorch 2.0, sm_75) results in:

```
ARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.0.dev20230123+cu118 with CUDA 1108 (you have 2.0.0.dev20230123+cu118)
    Python  3.10.9 (you have 3.10.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
Traceback (most recent call last):
  File "/home/alpha/.local/lib/python3.10/site-packages/xformers/_cpp_lib.py", line 117, in _register_extensions
    torch.ops.load_library(ext_specs.origin)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/_ops.py", line 640, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/alpha/.local/lib/python3.10/site-packages/xformers/_C.so: undefined symbol: __cudaRegisterLinkedBinary_9bc9d57a_7_spmm_cu_4ffa47c5
>>>
```

Messing with some of the architecture flags doesn't seem to make a difference, whatever is going wrong here is over my head.

**Comment by brucethemoose** [comment]
Also, while I assume this is already being done to some extent, a "native architecture only" build flag might be useful for those of us installing from source.

**Comment by danthe3rd** [comment]
Hi @brucethemoose 
What speedup do you expect with lto - and what kernels are you using?
I believe all of the recent kernels we released are completely inline and won't benefit from LTO optimizations
