### ISSUE TITLE
[BUG] RuntimeError: cutlassF: no kernel found to launch! with H100GPU

### ISSUE THREAD

**Issue by sdbds** [facebookresearch/xformers#729]
# 🐛 Bug

when i use xformers it happened

## Command

use both sd-webui and other project(like model train,llm and so on)

## To Reproduce

1.laungh webui with --xformers
2.train model with --xformers

Traceback (most recent call last):
  File "/media/h100/ai/sd-lastest/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/media/h100/ai/sd-lastest/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/media/h100/ai/sd-lastest/modules/processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "/media/h100/ai/sd-lastest/modules/processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/media/h100/ai/sd-lastest/modules/processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/media/h100/ai/sd-lastest/modules/sd_samplers_kdiffusion.py", line 358, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/media/h100/ai/sd-lastest/modules/sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "/media/h100/ai/sd-lastest/modules/sd_samplers_kdiffusion.py", line 358, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/modules/sd_samplers_kdiffusion.py", line 126, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/media/h100/ai/sd-lastest/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/media/h100/ai/sd-lastest/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "/media/h100/ai/sd-lastest/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/media/h100/ai/sd-lastest/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "/media/h100/ai/sd-lastest/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 272, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/h100/ai/sd-lastest/modules/sd_hijack_optimizations.py", line 342, in xformers_attention_forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=get_xformers_flash_attention_op(q, k, v))
  File "/media/h100/ai/sd-lastest/repositories/xformers/xformers/ops/fmha/__init__.py", line 192, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/media/h100/ai/sd-lastest/repositories/xformers/xformers/ops/fmha/__init__.py", line 290, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/media/h100/ai/sd-lastest/repositories/xformers/xformers/ops/fmha/__init__.py", line 310, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "/media/h100/ai/sd-lastest/repositories/xformers/xformers/ops/fmha/cutlass.py", line 175, in apply
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "/home/h100/miniconda3/envs/sdwl/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})

RuntimeError: cutlassF: no kernel found to launch!

## Expected behavior

i build xformers with H100 GPU and set TORCH_CUDA_ARCH_LIST=9.0,it not work.

## Environment

python -m xformers.info
xFormers 0.0.19+70161e5.d20230420
memory_efficient_attention.cutlassF:               available
memory_efficient_attention.cutlassB:               available
memory_efficient_attention.flshattF:               available
memory_efficient_attention.flshattB:               available
memory_efficient_attention.smallkF:                available
memory_efficient_attention.smallkB:                available
memory_efficient_attention.tritonflashattF:        available
memory_efficient_attention.tritonflashattB:        available
indexing.scaled_index_addF:                        available
indexing.scaled_index_addB:                        available
indexing.index_select:                             available
swiglu.dual_gemm_silu:                             available
swiglu.gemm_fused_operand_sum:                     available
swiglu.fused.p.cpp:                                available
is_triton_available:                               True
is_functorch_available:                            False
pytorch.version:                                   2.0.0+cu118
pytorch.cuda:                                      available
gpu.compute_capability:                            9.0
gpu.name:                                          NVIDIA H100 PCIe
build.info:                                        available
build.cuda_version:                                1108
build.python_version:                              3.10.9
build.torch_version:                               2.0.0+cu118
build.env.TORCH_CUDA_ARCH_LIST:                    6.0;6.1;7.0;7.5;8.0;8.6;9.0
build.env.XFORMERS_BUILD_TYPE:                     None
build.env.XFORMERS_ENABLE_DEBUG_ASSERTIONS:        None
build.env.NVCC_FLAGS:                              None
build.env.XFORMERS_PACKAGE_FROM:                   None
build.nvcc_version:                                11.8.89
source.privacy:                                    open source

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

PyTorch version: 2.0.0+cu118
OS: Ubuntu 20.04.6 LTS (x86_64)
- How you installed PyTorch (`conda`, `pip`, source):PIUP
- Build command you used (if compiling from source):export TORCH_CUDA_ARCH_LIST="6.0;6.1;7.0;7.5;8.0;8.6;9.0" pip install -e . 
- Python version:3.10.9
- CUDA/cuDNN version:11.8/8.9.0
- GPU models and configuration:GPU 0: NVIDIA H100 PCIe
- Any other relevant information:

[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.3
[pip3] open-clip-torch==2.7.0
[pip3] pytorch-lightning==1.9.4
[pip3] torch==2.0.0+cu118
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.0
[pip3] torchsde==0.2.5
[pip3] torchvision==0.15.1+cu118
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] open-clip-torch           2.7.0                    pypi_0    pypi
[conda] pytorch-lightning         1.9.4                    pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchsde                  0.2.5                    pypi_0    pypi
[conda] torchvision               0.15.1+cu118             pypi_0    pypi

**Comment by danthe3rd** [comment]
Hi @sdbds 
Unfortunately, we don't support H100 GPUs at the moment

**Comment by sdbds** [comment]
> Hi @sdbds Unfortunately, we don't support H100 GPUs at the moment

Thank u for replying,hope to support the use of H100 in the near future.

**Comment by sdbds** [comment]
test 0.0.20 ↓
CUDA error (third_party/flash-attention/csrc/flash_attn/src/fmha_fwd_launch_template.h:89): no kernel image is available for execution on the device

**Comment by danthe3rd** [comment]
We added experimental support for H100 GPUs (although not tested) in https://github.com/facebookresearch/xformers/commit/7a3838f3becbe0afd94da0d73d95ba98d02d1e9d - it's available in `0.0.20`.
However, we don't include kernels for H100s on the binaries at the moment, so you would have to install [xformers from source](https://github.com/facebookresearch/xformers#installing-xformers) to use it

**Comment by sdbds** [comment]
> We added experimental support for H100 GPUs (although not tested) in [7a3838f](https://github.com/facebookresearch/xformers/commit/7a3838f3becbe0afd94da0d73d95ba98d02d1e9d) - it's available in `0.0.20`. However, we don't include kernels for H100s on the pip/conda binaries at the moment, so you would have to install [xformers from source](https://github.com/facebookresearch/xformers#installing-xformers) to use it

ok ,it works well now,thank you~

**Comment by saubcy** [comment]
> ARCH

Jetson orin have the same issues，and the arch is 8.7，can orin support modify like this？

**Comment by saubcy** [comment]
Jetson orin have the same issues，and the arch is 8.7，can orin support modify like this？
