### ISSUE TITLE
xformers fails to build in environment with pytorch 1.13.1 if mkl is at version 2023 rather than 2021

### ISSUE THREAD

**Issue by zagglez** [facebookresearch/xformers#745]
Docker environment
FROM nvcr.io/nvidia/pytorch:22.12-py3

mkl versions present:
mkl                         2021.1.1
mkl-devel               2021.1.1
mkl-include             2021.1.1

if I upgrade mkl etc to 2023 version then xformers build no longer picks up libmkl_intel_lp64.so.1  (and presumably the other libmkl files)

 > [27/41] RUN python3 -m pip install --upgrade --no-cache-dir     git+https://github.com/facebookresearch/xformers.git@main#egg=xformers:                                
#0 0.587 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com                                                                                         
#0 0.591 Collecting xformers                                                                                                                                              
#0 0.591   Cloning https://github.com/facebookresearch/xformers.git (to revision main) to /tmp/pip-install-dspb52nu/xformers_9ba46f3d74c548caa15b28ce751f7ee8             
#0 0.593   Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/xformers.git /tmp/pip-install-dspb52nu/xformers_9ba46f3d74c548caa15b28ce751f7ee8
#0 4.153   Resolved https://github.com/facebookresearch/xformers.git to commit 6425fd0cacb1a6579aa2f0c4a570b737cb10e9c3
#0 4.154   Running command git submodule update --init --recursive -q
#0 18.51   Preparing metadata (setup.py): started
#0 18.63   Preparing metadata (setup.py): finished with status 'error'
#0 18.64   error: subprocess-exited-with-error
#0 18.64   
#0 18.64   × python setup.py egg_info did not run successfully.
#0 18.64   │ exit code: 1
#0 18.64   ╰─> [12 lines of output]
#0 18.64       Traceback (most recent call last):
#0 18.64         File "<string>", line 2, in <module>
#0 18.64         File "<pip-setuptools-caller>", line 34, in <module>
#0 18.64         File "/tmp/pip-install-dspb52nu/xformers_9ba46f3d74c548caa15b28ce751f7ee8/setup.py", line 23, in <module>
#0 18.64           import torch
#0 18.64         File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 191, in <module>
#0 18.64           _load_global_deps()
#0 18.64         File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 153, in _load_global_deps
#0 18.64           ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
#0 18.64         File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
#0 18.64           self._handle = _dlopen(self._name, mode)
#0 18.64       OSError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
#0 18.64       [end of output]
#0 18.64

**Comment by zagglez** [comment]
Builds fine if mkl is left at 2021 version.
