### ISSUE TITLE
FlashAttention gives error with attention mask / attention bias

### ISSUE THREAD

**Issue by dguo98** [facebookresearch/xformers#750]
# 🐛 Bug

If i use MemoryEfficientAttentionFlashAttentionOp as my attention op for memory efficient attention, and use attention bias, it will give me errors :(

## Command
```
import math
import torch
import xformers.ops.fmha as fmha
from xformers.ops import MemoryEfficientAttentionFlashAttentionOp as flash_attn_op

B, M, H, K = 1, 1024, 2, 64
dtype = torch.float16
device = "cuda"

q, k, v = [torch.randn([B, M, H, K], dtype=dtype, device=device) for _ in range(3)]
mask = torch.zeros([B, H, M, M], dtype=dtype, device=device)
mask[:, :, :256, :256] = -math.inf

torch.manual_seed(0)
q = torch.randn([160,1100,64], dtype=dtype, device=device)
k=torch.randn([160,77,64], dtype=dtype, device=device)
v=torch.randn([160,77,64],dtype=dtype,device=device)
mask=torch.zeros([160,1100,77],dtype=dtype,device=device)
mask[:,:,30:]=-math.inf

add8 = 8 - mask.shape[-1] % 8

new_dtype=mask.type()
new_device=mask.get_device()
print("new_dtype=", new_dtype)
print("new_device=",new_device)
tmp_mask = torch.zeros([mask.shape[0],mask.shape[1], mask.shape[2]+add8]).type(new_dtype).to(new_device) #,dtype=new_dtype,device=device) #, dtype=mask.type(), device=mask.get_device())
tmp_mask[:,:,:mask.shape[2]] = mask
out = fmha.memory_efficient_attention(q, k, v, attn_bias=tmp_mask[:,:,:mask.shape[2]], op=flash_attn_op)
print(out.sum())
```

## Expected behavior

Traceback (most recent call last):
  File "sandbox.py", line 29, in <module>
    out = fmha.memory_efficient_attention(q, k, v, attn_bias=tmp_mask[:,:,:mask.shape[2]], op=flash_attn_op)
  File "/root/miniconda3/envs/sd/lib/python3.8/site-packages/xformers/ops/fmha/__init__.py", line 192, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/root/miniconda3/envs/sd/lib/python3.8/site-packages/xformers/ops/fmha/__init__.py", line 290, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/root/miniconda3/envs/sd/lib/python3.8/site-packages/xformers/ops/fmha/__init__.py", line 308, in _memory_efficient_attention_forward
    _ensure_op_supports_or_raise(ValueError, "memory_efficient_attention", op, inp)
  File "/root/miniconda3/envs/sd/lib/python3.8/site-packages/xformers/ops/fmha/dispatch.py", line 55, in _ensure_op_supports_or_raise
    raise exc_type(
ValueError: Operator `memory_efficient_attention` does not support inputs:
     query       : shape=(160, 1100, 1, 64) (torch.float16)
     key         : shape=(160, 77, 1, 64) (torch.float16)
     value       : shape=(160, 77, 1, 64) (torch.float16)
     attn_bias   : <class 'torch.Tensor'>
     p           : 0.0
`flshattF` is not supported because:
    attn_bias type is <class 'torch.Tensor'>

## Environment

PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (conda-forge gcc 9.5.0-19) 9.5.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:55:52)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.55
GPU models and configuration: 
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe
GPU 4: NVIDIA A100 80GB PCIe
GPU 5: NVIDIA A100 80GB PCIe
GPU 6: NVIDIA A100 80GB PCIe
GPU 7: NVIDIA A100 80GB PCIe

Nvidia driver version: 510.108.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] open-clip-torch==2.7.0
[pip3] pytorch-lightning==1.5.0
[pip3] torch==1.12.1
[pip3] torch-fidelity==0.3.0
[pip3] torchaudio==0.12.1
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.6.0              hd754f66_10    deepmodeling
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] open-clip-torch           2.7.0                    pypi_0    pypi
[conda] pytorch                   1.12.1          py3.8_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-lightning         1.5.0                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torchaudio                0.12.1               py38_cu116    pytorch
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchvision               0.13.1               py38_cu116    pytorch

## Additional context

If I don't pass in flash attention as my op, it works fine.

**Comment by danthe3rd** [comment]
Flash attention does not support attention bias (except for a simple causal mask) - so this is expected.
