### ISSUE TITLE
Unable to install xFormers on Mac M1Max

### ISSUE THREAD

**Issue by vdnew** [facebookresearch/xformers#775]
# 🐛 Bug

Unable to install xFormers on Mac M1Max , have tried to install in many ways.

## Command

`pip3 install ninja`

`pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers`

## To Reproduce

1. pip3 install ninja
2. pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
3.

```
(lend) vishvdeeepdasadiya@vishvdeeeps-MacBook-Pro src % pip install ninja
Collecting ninja
  Using cached ninja-1.11.1-py2.py3-none-macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (270 kB)
Installing collected packages: ninja
Successfully installed ninja-1.11.1
(lend) vishvdeeepdasadiya@vishvdeeeps-MacBook-Pro src % pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
Using pip 23.1.2 from /Users/vishvdeeepdasadiya/Documents/LendAssist/src/lend/lib/python3.9/site-packages/pip (python 3.9)
Collecting xformers
  Cloning https://github.com/facebookresearch/xformers.git (to revision main) to /private/var/folders/dd/c2stl7hj59qcmn9_qmbtcfmh0000gn/T/pip-install-iyesoquw/xformers_477c827a90074775aab9d0e40881504b
  Running command git version
  git version 2.39.2 (Apple Git-143)
  Running command git clone --filter=blob:none https://github.com/facebookresearch/xformers.git /private/var/folders/dd/c2stl7hj59qcmn9_qmbtcfmh0000gn/T/pip-install-iyesoquw/xformers_477c827a90074775aab9d0e40881504b
  Cloning into '/private/var/folders/dd/c2stl7hj59qcmn9_qmbtcfmh0000gn/T/pip-install-iyesoquw/xformers_477c827a90074775aab9d0e40881504b'...
  Updating files:   0% (2/692)
  Updating files:   1% (7/692)
  Updating files:   2% (14/692)
  Updating files:   3% (21/692)
  Updating files:   4% (28/692)
  Updating files:   5% (35/692)
  Updating files:   6% (42/692)
  Updating files:   7% (49/692)
  Updating files:   8% (56/692)
  Updating files:   9% (63/692)
  Updating files:  10% (70/692)
  Updating files:  11% (77/692)
  Updating files:  12% (84/692)
  Updating files:  13% (90/692)
  Updating files:  14% (97/692)
  Updating files:  15% (104/692)
  Updating files:  16% (111/692)
  Updating files:  17% (118/692)
  Updating files:  18% (125/692)
  Updating files:  19% (132/692)
  Updating files:  20% (139/692)
  Updating files:  21% (146/692)
  Updating files:  22% (153/692)
  Updating files:  23% (160/692)
  Updating files:  24% (167/692)
  Updating files:  25% (173/692)
  Updating files:  26% (180/692)
  Updating files:  27% (187/692)
  Updating files:  28% (194/692)
  Updating files:  29% (201/692)
  Updating files:  30% (208/692)
  Updating files:  31% (215/692)
  Updating files:  32% (222/692)
  Updating files:  33% (229/692)
  Updating files:  34% (236/692)
  Updating files:  35% (243/692)
  Updating files:  36% (250/692)
  Updating files:  37% (257/692)
  Updating files:  38% (263/692)
  Updating files:  39% (270/692)
  Updating files:  40% (277/692)
  Updating files:  41% (284/692)
  Updating files:  42% (291/692)
  Updating files:  43% (298/692)
  Updating files:  44% (305/692)
  Updating files:  45% (312/692)
  Updating files:  46% (319/692)
  Updating files:  47% (326/692)
  Updating files:  48% (333/692)
  Updating files:  49% (340/692)
  Updating files:  50% (346/692)
  Updating files:  51% (353/692)
  Updating files:  52% (360/692)
  Updating files:  53% (367/692)
  Updating files:  54% (374/692)
  Updating files:  55% (381/692)
  Updating files:  56% (388/692)
  Updating files:  57% (395/692)
  Updating files:  58% (402/692)
  Updating files:  59% (409/692)
  Updating files:  60% (416/692)
  Updating files:  61% (423/692)
  Updating files:  62% (430/692)
  Updating files:  63% (436/692)
  Updating files:  64% (443/692)
  Updating files:  65% (450/692)
  Updating files:  66% (457/692)
  Updating files:  67% (464/692)
  Updating files:  68% (471/692)
  Updating files:  69% (478/692)
  Updating files:  70% (485/692)
  Updating files:  71% (492/692)
  Updating files:  72% (499/692)
  Updating files:  73% (506/692)
  Updating files:  74% (513/692)
  Updating files:  75% (519/692)
  Updating files:  76% (526/692)
  Updating files:  77% (533/692)
  Updating files:  78% (540/692)
  Updating files:  79% (547/692)
  Updating files:  80% (554/692)
  Updating files:  81% (561/692)
  Updating files:  82% (568/692)
  Updating files:  83% (575/692)
  Updating files:  84% (582/692)
  Updating files:  85% (589/692)
  Updating files:  86% (596/692)
  Updating files:  87% (603/692)
  Updating files:  88% (609/692)
  Updating files:  89% (616/692)
  Updating files:  90% (623/692)
  Updating files:  91% (630/692)
  Updating files:  92% (637/692)
  Updating files:  93% (644/692)
  Updating files:  94% (651/692)
  Updating files:  95% (658/692)
  Updating files:  96% (665/692)
  Updating files:  97% (672/692)
  Updating files:  98% (679/692)
  Updating files:  99% (686/692)
  Updating files: 100% (692/692)
  Updating files: 100% (692/692), done.
  Running command git show-ref main
  9d3d92cbe5ec178c6aa0f45a930efe466fa1ff46 refs/heads/main
  9d3d92cbe5ec178c6aa0f45a930efe466fa1ff46 refs/remotes/origin/main
  Running command git symbolic-ref -q HEAD
  refs/heads/main
  Resolved https://github.com/facebookresearch/xformers.git to commit 9d3d92cbe5ec178c6aa0f45a930efe466fa1ff46
  Running command git submodule update --init --recursive -q
  Running command git rev-parse HEAD
  9d3d92cbe5ec178c6aa0f45a930efe466fa1ff46
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
  Collecting wheel
    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-68.0.0 wheel-0.40.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "/Users/vishvdeeepdasadiya/Documents/LendAssist/src/lend/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/vishvdeeepdasadiya/Documents/LendAssist/src/lend/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/vishvdeeepdasadiya/Documents/LendAssist/src/lend/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/dd/c2stl7hj59qcmn9_qmbtcfmh0000gn/T/pip-build-env-1y8cf5a1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/dd/c2stl7hj59qcmn9_qmbtcfmh0000gn/T/pip-build-env-1y8cf5a1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/dd/c2stl7hj59qcmn9_qmbtcfmh0000gn/T/pip-build-env-1y8cf5a1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/dd/c2stl7hj59qcmn9_qmbtcfmh0000gn/T/pip-build-env-1y8cf5a1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 23, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/vishvdeeepdasadiya/Documents/LendAssist/src/lend/bin/python3 /Users/vishvdeeepdasadiya/Documents/LendAssist/src/lend/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /var/folders/dd/c2stl7hj59qcmn9_qmbtcfmh0000gn/T/tmpoarvupyd
  cwd: /private/var/folders/dd/c2stl7hj59qcmn9_qmbtcfmh0000gn/T/pip-install-iyesoquw/xformers_477c827a90074775aab9d0e40881504b
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

## Expected behavior

Expected behaviour should be installed properly.

## Environment
You can run the script with:

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 (default, May  7 2023, 23:32:44)  [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] torch==2.0.1

**Comment by danthe3rd** [comment]
Hi,
Unfortunately xFormers does not support MacOS

**Comment by vdnew** [comment]
Hey @danthe3rd, Thank you for the response. Is there any work around for this?

**Comment by danthe3rd** [comment]
CUDA no longer supports MacOS, so we can't build the custom components we have on MacOS unfortunately

**Comment by rovo79** [comment]
Might be helpful to add a note to the [README.md](https://github.com/facebookresearch/xformers/blob/f057b130fc83f3570c7f48d41761c472a529460b/README.md) that Apple M1/M2 not supported.

**Comment by rovo79** [comment]
#858
https://github.com/facebookresearch/xformers/issues/858#issuecomment-1729440951
