### ISSUE TITLE
[Help] xformers is not supported by Stable Diffusion Dreambooth

### ISSUE THREAD

**Issue by venshine** [facebookresearch/xformers#777]
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
conda install xformers -c xformers/label/dev
```
```
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements



If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: dc413a14379b165355502d9f65856c40a4bb5b6f
Successfully installed accelerate-0.19.0 fastapi-0.94.1 gitpython-3.1.31 transformers-4.29.2

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.21.dev556+git.9d3d92c installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.


Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72



Launching Web UI with arguments: --enable-insecure-extension-access --share --listen --api --opt-sdp-attention
```
I have already installed xformers through the above two commands, and when running stable-diffusion, information about the installation of xformers can be printed out. However, when I use stable-diffusion's Dreambooth to train the model, the following exception is prompted. What should I do?
```
Initializing dreambooth training...
Pre-processing images: classifiers_0: : 48it [00:00, 5941.99it/s]
We need a total of 120 class images.: : 48it [00:00, 6289.10it/s]     | 0/24 [00:00<?, ?it/s]
Generating 120 class images for training...
                                                                                            Traceback (most recent call last): 0%|                                | 0/120 [00:00<?, ?it/s]
  File "/mnt/disk-1/venshine/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/mnt/disk-1/venshine/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1548, in main
    return inner_loop()
  File "/mnt/disk-1/venshine/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/mnt/disk-1/venshine/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 246, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "/mnt/disk-1/venshine/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 153, in generate_classifiers
    builder = ImageBuilder(
  File "/mnt/disk-1/venshine/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 110, in __init__
    self.image_pipe.enable_xformers_memory_efficient_attention()
  File "/home/venshine/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1448, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/home/venshine/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1474, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/venshine/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1464, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/venshine/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/venshine/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/venshine/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/venshine/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/venshine/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/venshine/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/models/attention.py", line 105, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Generating class images 0/120::   0%|                                | 0/120 [00:02<?, ?it/s]
Restored system models.
Duration: 00:00:05
```

**Comment by danthe3rd** [comment]
Hi,
It looks like you installed xformers correctly. I would recommend opening an issue on `Dreambooth` as I'm not exactly sure how this works (and how it uses xformers)

**Comment by venshine** [comment]
> Hi, It looks like you installed xformers correctly. I would recommend opening an issue on `Dreambooth` as I'm not exactly sure how this works (and how it uses xformers)

It's my fault, the command to start my script did not include the --xformers parameter.
