### ISSUE TITLE
Error:     xFormers wasn't build with CUDA support

### ISSUE THREAD

**Issue by quintendewilde** [facebookresearch/xformers#800]
I'm suddenly unaible to run my project on Google Colab. It worked 4 days ago and now whatever I do i get the issue below.

I'm using this Colab (Pro with A100): [Stable Diffusion, Deforum]
(https://colab.research.google.com/github/sagiodev/stablediffusion_webui/blob/master/StableDiffusionUI_ngrok_sagiodev.ipynb)

I'm using:  %pip install -q xformers
To install xformers

```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 1.13.1+cu117)
    Python  3.10.11 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
ngrok authtoken detected, trying to connect...

I get the same issue after clean install

Full issue

*START OF TRACEBACK*
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/run_deforum.py", line 78, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root)
  File "/content/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/render.py", line 548, in render_animation
    image = generate(args, keys, anim_args, loop_args, controlnet_args, root, parseq_adapter, frame_idx, sampler_name=scheduled_sampler_name)
  File "/content/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/generate.py", line 56, in generate
    return generate_inner(args, keys, anim_args, loop_args, controlnet_args, root, parseq_adapter, frame, sampler_name)
  File "/content/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/generate.py", line 210, in generate_inner
    processed = processing.process_images(p_txt)
  File "/content/stable-diffusion-webui/modules/processing.py", line 620, in process_images
    res = process_images_inner(p)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/content/stable-diffusion-webui/modules/processing.py", line 739, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/content/stable-diffusion-webui/modules/processing.py", line 992, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 439, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 278, in launch_sampling
    return func()
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 439, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 158, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_unet.py", line 91, in UNetModel_forward
    return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 272, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 461, in xformers_attention_forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=get_xformers_flash_attention_op(q, k, v))
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 192, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 290, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 306, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/dispatch.py", line 94, in _dispatch_fw
    return _run_priority_list(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/dispatch.py", line 69, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(2, 4096, 8, 40) (torch.float16)
     key         : shape=(2, 4096, 8, 40) (torch.float16)
     value       : shape=(2, 4096, 8, 40) (torch.float16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    Operator wasn't built - see `python -m xformers.info` for more info
    requires a GPU with compute capability > 7.5
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    requires A100 GPU
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    Operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float16 (supported: {torch.float32})
    max(query.shape[-1] != value.shape[-1]) > 32
    Operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 40
*END OF TRACEBACK*

User friendly error message:
Error: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(2, 4096, 8, 40) (torch.float16)
     key         : shape=(2, 4096, 8, 40) (torch.float16)
     value       : shape=(2, 4096, 8, 40) (torch.float16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    Operator wasn't built - see `python -m xformers.info` for more info
    requires a GPU with compute capability > 7.5
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    requires A100 GPU
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    Operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float16 (supported: {torch.float32})
    max(query.shape[-1] != value.shape[-1]) > 32
    Operator wasn't built - see `python -m xformers.info` for more info
```

**Comment by quintendewilde** [comment]
UPDATE | I changed to A100 and still get the error:

Error: 'No operator found for `memory_efficient_attention_forward` with inputs: query : shape=(2, 4096, 8, 40) (torch.float16) key : shape=(2, 4096, 8, 40) (torch.float16) value : shape=(2, 4096, 8, 40) (torch.float16) attn_bias : p : 0.0 `flshattF` is not supported because: xFormers wasn't build with CUDA support Operator wasn't built - see `python -m xformers.info` for more info `tritonflashattF` is not supported because: xFormers wasn't build with CUDA support `cutlassF` is not supported because: xFormers wasn't build with CUDA support Operator wasn't built - see `python -m xformers.info` for more info `smallkF` is not supported because: xFormers wasn't build with CUDA support dtype=torch.float16 (supported: {torch.float32}) max(query.shape[-1] != value.shape[-1]) > 32 Operator wasn't built - see `python -m xformers.info` for more info unsupported embed per head: 40'. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \. Full error message is in your terminal/ cli.
Time taken: 0.68sTorch active/reserved: 2117/2130 MiB, Sys VRAM: 3947/40514 MiB (9.74%)

**Comment by quintendewilde** [comment]
> Hi, can you try to upgrade to pytorch 2.0.1?

I've tried !pip install torch==2.0.1+cu118 torchvision==0.14.1+cu117 torchtext==0.14.1 torchaudio==0.13.1 torchdata==0.5.1 --extra-index-url https://download.pytorch.org/whl/cu117

But it still shows I'm running on the older version. (same error)

**Comment by danthe3rd** [comment]
This will give you the PyTorch version:
```python
import torch
print(torch.__version__)
print(torch.__file__)
```

**Comment by quintendewilde** [comment]
Upgrading worked, had to reinstall/rerun everything though to make the upgrade

**Comment by AnasHXH** [comment]
I have this error:

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_cpu_threads_per_process` was set to `32` to improve out-of-box performance when training on CPUs
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cu118)
    Python  3.8.18 (you have 3.8.5)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
10/15/2023 14:46:49 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: fp16

{'timestep_spacing', 'variance_type', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
{'scaling_factor', 'force_upcast'} was not found in config. Values will be initialized to default values.
{'projection_class_embeddings_input_dim', 'attention_type', 'encoder_hid_dim', 'conv_out_kernel', 'time_embedding_dim', 'addition_embed_type_num_heads', 'dropout', 'addition_embed_type', 'resnet_skip_time_act', 'time_embedding_type', 'num_attention_heads', 'transformer_layers_per_block', 'class_embeddings_concat', 'time_cond_proj_dim', 'cross_attention_norm', 'timestep_post_act', 'resnet_out_scale_factor', 'mid_block_only_cross_attention', 'encoder_hid_dim_type', 'conv_in_kernel', 'time_embedding_act_fn', 'addition_time_embed_dim'} was not found in config. Values will be initialized to default values.
10/15/2023 14:46:53 - INFO - __main__ - Initializing the InstructPix2Pix UNet from the pretrained UNet.
Traceback (most recent call last):
  File "diffusers/examples/instruct_pix2pix/train_instruct_pix2pix.py", line 1062, in <module>
    main()
  File "diffusers/examples/instruct_pix2pix/train_instruct_pix2pix.py", line 530, in main
    unet.enable_xformers_memory_efficient_attention()
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 290, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 254, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 254, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 222, in set_use_memory_efficient_attention_xformers
    raise e
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 216, in set_use_memory_efficient_attention_xformers
    _ = xformers.ops.memory_efficient_attention(
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/xformers/ops/fmha/__init__.py", line 223, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/xformers/ops/fmha/__init__.py", line 321, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/xformers/ops/fmha/__init__.py", line 337, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/xformers/ops/fmha/dispatch.py", line 120, in _dispatch_fw
    return _run_priority_list(
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/xformers/ops/fmha/dispatch.py", line 63, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    xFormers wasn't build with CUDA support
    attn_bias type is <class 'NoneType'>
    operator wasn't built - see `python -m xformers.info` for more info
`flshattF@0.0.0` is not supported because:
    xFormers wasn't build with CUDA support
    requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
    requires GPU with sm80 minimum compute capacity, e.g., A100/H100/L4
    Only work on pre-MLIR triton for now
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 40
Traceback (most recent call last):
  File "/home/akoubaa/anaconda3/envs/SDM/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/akoubaa/anaconda3/envs/SDM/lib/python3.8/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/akoubaa/anaconda3/envs/SDM/bin/python', 'diffusers/examples/instruct_pix2pix/train_instruct_pix2pix.py', '--pretrained_model_name_or_path=timbrooks/instruct-pix2pix', '--train_data_dir=train_noise_blure_images_with_prompts', '--enable_xformers_memory_efficient_attention', '--resolution=512', '--random_flip', '--train_batch_size=2', '--gradient_accumulation_steps=2', '--gradient_checkpointing', '--max_train_steps=18005', '--checkpointing_steps=4500', '--checkpoints_total_limit=1', '--learning_rate=5e-05', '--max_grad_norm=1', '--lr_warmup_steps=0', '--conditioning_dropout_prob=0.05', '--mixed_precision=fp16', '--seed=42']' returned non-zero exit status 1.
_________________________________________________________________________________________________
my torch version is :
![image](https://github.com/facebookresearch/xformers/assets/65374131/1d58344f-80b7-4a1e-b8bd-061bbdc466b2)

can you solve my error?
