### ISSUE TITLE
ModuleNotFoundError: No module named 'flash_attn'

### ISSUE THREAD

**Issue by goldhuang** [facebookresearch/xformers#826]
After commit `2d3a2217c263419243b70c53f725213d1c386b0f`, I always get error below. I'm on A10G.
```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/xformers/ops/fmha/triton.py", line 17, in <module>
    from flash_attn.flash_attn_triton import (
ModuleNotFoundError: No module named 'flash_attn'
```

```
    import xformers.ops
  File "/opt/venv/lib/python3.10/site-packages/xformers/ops/__init__.py", line 8, in <module>
    from .fmha import (
  File "/opt/venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 10, in <module>
    from . import cutlass, decoder, flash, small_k, triton
  File "/opt/venv/lib/python3.10/site-packages/xformers/ops/fmha/triton.py", line 39, in <module>
    flash_attn = import_module_from_path(
  File "/opt/venv/lib/python3.10/site-packages/xformers/ops/fmha/triton.py", line 36, in import_module_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
```

**Comment by danthe3rd** [comment]
Hi,
This should be fixed in https://github.com/facebookresearch/xformers/commit/ba5b4496e413984edd4b3deb0f47434fa62720a7
