### ISSUE TITLE
63eeb44 / 0.0.21 breaks 'pip install xformers'

### ISSUE THREAD

**Issue by dusty-nv** [facebookresearch/xformers#831]
Since xformers 0.0.21 release, 'pip install xformers` has started failing with:

```
fatal: not a git repository (or any of the parent directories): .git
subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--always']' returned non-zero exit status 128.
```

Seems related to https://github.com/facebookresearch/xformers/commit/63eeb44734bea1e04e64b5ba6cf5eee3bc4e24f5 and this code that was added:

```python
flash_version = subprocess.check_output(
                ["git", "describe", "--tags", "--always"],
                cwd=Path(__file__).parent / "third_party" / "flash-attention",
            ).decode("ascii")[:-1]
```

Presumably the pip source doesn't have the .git structure

```bash
$ pip install -U xformers
Using pip 23.2.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
Collecting xformers
  Downloading xformers-0.0.21.tar.gz (22.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.3/22.3 MB 23.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  fatal: not a git repository (or any of the parent directories): .git
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/tmp/pip-install-1wrbodoa/xformers_148bf17c012a43ebac8de26e4ba0bc91/setup.py", line 407, in <module>
      extensions, extensions_metadata = get_extensions()
    File "/tmp/pip-install-1wrbodoa/xformers_148bf17c012a43ebac8de26e4ba0bc91/setup.py", line 266, in get_extensions
      flash_version = subprocess.check_output(
    File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--always']' returned non-zero exit status 128.
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-1wrbodoa/xformers_148bf17c012a43ebac8de26e4ba0bc91/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-xvrzriu4
  cwd: /tmp/pip-install-1wrbodoa/xformers_148bf17c012a43ebac8de26e4ba0bc91/
  Preparing metadata (setup.py): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by danthe3rd** [comment]
Hey @dusty-nv and thanks for reporting this bug!

It looks like it's indeed an issue with the source distribution. In the meantime, you can build from source. We will try to fix this asap

**Comment by danthe3rd** [comment]
This was fixed over a month ago. Closing
