### ISSUE TITLE
Question: is xformers support compilation from source with cuda12.1 ?

### ISSUE THREAD

**Issue by thibautlavril** [facebookresearch/xformers#905]
# ❓ Questions and Help

Hello!

I am encountering some segmentation fault when trying to compile xformers from source (current main, commit "3f74d96b0d40058f036b016eb4e9e92c937cfdd9")

Python 3.8.10
torch: 2.1.0
cuda: 12.1
TORCH_CUDA_ARCH_LIST="8.6;9.0"

I tried with MAX_JOBS=2 to reduce memory pressure, but same issue

I wanted to double check that xformers was indeed supposed to support compilation from source with this CUDA version while continuing investigation on our side

Thanks!

```
...
ptxas info    : Function properties for _ZN5flash22copy_rotary_contiguousILb1ELb0EN4cute10ViewEngineINS1_8gmem_ptrIN7cutlass6half_tEEEEENS1_6LayoutINS1_5tupleIJNS9_IJNS1_1CILi8EEENSA_ILi1EEEEEENSA_ILi16EEESC_EEENS9_IJNS9_IJSC_NSA_ILi0EEEEEEjSG_EEEEES7_SJ_S7_NS8_INS9_IJNS9_IJSC_SB_EEESE_SC_EEENS9_IJNS9_IJSG_SC_EEEiSG_EEEEENS2_INS1_23ArithmeticTupleIteratorINS1_15ArithmeticTupleIJiiEEEEEEENS8_ISF_NS9_IJNS9_IJNS1_11ScaledBasisISC_Li1EEESG_EEENSU_ISE_Li0EEESG_EEEEEEEvRKNS1_6TensorIT1_T2_EERNS10_IT3_T4_EERKNS10_IT5_T6_EES1E_RKNS10_IT7_T8_EEiiii
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for _ZN5flash4gemmILb0ELb0EN4cute6TensorINS1_13array_alignedIfLm128ELm16EEENS1_6LayoutINS1_5tupleIJNS6_IJNS1_1CILi2EEES8_EEENS7_ILi1EEENS7_ILi32EEEEEENS6_IJNS6_IJSA_S8_EEENS7_ILi0EEENS7_ILi4EEEEEEEEEENS2_INS3_IN7cutlass6half_tELm32ELm16EEENS5_INS6_IJNS6_IJS8_S8_S8_EEESA_S9_EEENS6_IJNS6_IJSA_S8_SF_EEESE_NS6_IJNS7_ILi8EEENS7_ILi16EEEEEEEEEEEEENS2_INS3_ISK_Lm512ELm16EEENS5_INS6_IJS9_SB_S9_EEENS6_IJSD_SF_NS6_IJNS7_ILi128EEENS7_ILi256EEEEEEEEEEEEENS2_INS1_10ViewEngineINS1_8smem_ptrISK_EEEENS5_INS6_IJNS6_IJSP_SA_EEESA_S9_EEENS6_IJNS6_IJSA_SE_EEESE_NS6_IJiiEEEEEEEEEENS2_IS16_NS5_INS6_IJS17_SQ_S9_EEENS6_IJS19_NS7_ILi1024EEES1A_EEEEEEENS1_8TiledMMAINS1_8MMA_AtomIJNS1_28SM80_16x8x16_F32F16F16F32_TNEEEENS5_INS6_IJSF_SA_SA_EEENS6_IJSA_SE_SE_EEEEENS5_INS6_IJSA_S8_SA_EEENS6_IJSE_SA_SE_EEEEENS6_IJNS1_10UnderscoreES1T_S1T_EEEEENS1_9TiledCopyINS1_9Copy_AtomIJNS1_17SM75_U32x4_LDSM_NESK_EEENS5_INS6_IJNS6_IJSF_SP_SF_EEENS6_IJSM_NS6_IJSA_SA_EEEEEEEEENS6_IJNS6_IJSX_SA_SQ_EEENS6_IJNS6_IJNS7_ILi64EEESP_NS7_ILi512EEEEEENS6_IJSE_SE_EEEEEEEEEEENS6_IJS25_SQ_EEEEENS1W_IS1Z_NS5_INS6_IJS20_NS6_IJS9_NS6_IJS8_SA_EEEEEEEEENS6_IJNS6_IJSB_SA_SE_EEENS6_IJNS6_IJSQ_SX_EEENS6_IJSP_SE_EEEEEEEEEEENS6_IJSQ_SQ_EEEEENS1_7ThrCopyIS2D_iEENS2P_IS2O_iEEEEvRT1_RT2_RT3_RKT4_RKT5_T6_T7_T8_T9_T10_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
Segmentation fault (core dumped)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '2']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 419, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 364, in build_extensions
    super().build_extensions()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by siddartha-RE** [comment]
Same here. I even tried with MAX_JOBS=1 and hit this error.

**Comment by danthe3rd** [comment]
Hi, building from source is indeed supported.
What OS are you using? We're working to add wheels for cu12 with Flash-Attention - hopefully available today or tomorrow

**Comment by akowalsk** [comment]
I can't speak for the OP, but I'm running ubuntu 22.04 with python 3.10. (I'm also using PyTorch 2.1.0 on CUDA 12.1)  I compile PyTorch from source for my specific cuda architectures and usually build dependent packages (like xformers) from source for the same reason.

I can say that it seems to have something to do with flash-attention, since it complies just fine if I add `XFORMERS_DISABLE_FLASH_ATTN=1`, which I do not want to do.  It also compiles without error when I use the v0.0.21 tag.  All 4 of the v0.0.22 tags give me the same Segmentation Fault error.  

When I compile the flash-attention project myself (tried 2.3.2, the same version 0.0.22.post4 is using), it works just fine.  Having that installed before trying to compile xformers doesn't seem to make a difference.

**Comment by danthe3rd** [comment]
@akowalsk you can also set `XFORMERS_DISABLE_FLASH_ATTN=1`, and install flash-attention yourself, xformers should be able to use it, as long as you use a compatible version (2.3.2 should be fine). Flash-Attention should appear as `available` in `python -m xformers.info`

**Comment by thibautlavril** [comment]
Thanks @danthe3rd fro the answer!

I am using an enroot container with ubuntu 22.04

When I tried to install with pip I had another error.

**Comment by thibautlavril** [comment]
@danthe3rd Thanks for the answer!

when trying to pip install, I have this issue, so that's why I tried installing from source

```
>>> import xformers
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0)
    Python  3.8.18 (you have 3.8.10)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
  ```
  Pytorch is built from source in my case
  
  ```
  python -c "import torch;print(torch.__version__);print(torch.version.cuda);print(torch.cuda.nccl.version());print(torch.cuda.get_arch_list())"
2.1.0
12.1
(2, 19, 3)
['sm_86', 'sm_90']
```
  
 Will try to see if I can update the python of my container to see if the issue can come from the python version mismatch

**Comment by danthe3rd** [comment]
Can you set `XFORMERS_MORE_DETAILS=1 ` to see the exact error message?

**Comment by arvindsun** [comment]
If others want to test, I have a patch to fix cuda12.1 compilation from source. If other folks could test it please do.

 https://github.com/facebookresearch/xformers/pull/935

**Comment by pavelToman** [comment]
Hello, 
I am trying to install xformers on UGent HPC via EasyBuild.
We have RHEL 8/9 on clusters, python 3.11.3, GCC 12.3.0.
I have dependencies already compiled and installed: 
- CUDA-12.1.1
- PyTorch 2.1.2-with-CUDA 
- flash-attention-2.6.3-with-CUDA
- CUTLASS-3.4.0-with-CUDA

I need to build and install xformers-0.0.23.post1 with CUDA support from source (as a dependency for vllm-0.4.0).
I set some envars:
export MAX_JOBS=1
export TORCH_CUDA_ARCH_LIST="5.2;6.0;7.0;7.5;8.0;8.6;9.0"

I am hitting the very same error as describe here during pip install:

```
ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '1']' returned non-zero exit status 1.
...
File "/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
File "/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
```

Could you help me please with this?
